// Local tick 2026-09-10, batch 1. Four Tabelog locales read per shop (en/tw/kr/th).
import { put, T } from './_tick_lib.mjs';

const TB = u => `https://tabelog.com/en/tokyo/${u}/dtlmenu/`;

put('s36', 'tokyo_namiki_yabu_soba', {
  verified: 'partial',
  confidence: 'medium',
  sources: [TB('A1311/A131102/13003650')],
  price_note:
    'Full 15-row menu read off Tabelog in four locales (en/tw/kr/th), 東京都台東区雷門2-11-9, one minute from Kaminarimon; 36 seats, 11:00–19:30 (L.O. 19:00), closed Wednesday and Thursday, average spend ¥1,000–1,999. ⚠ THE PRICES ARE STAMPED 「As of March 7, 2023」 ON THE PAGE ITSELF — they are two and a half years old at the time of reading and are recorded as what the shop last published, not as what it charges today. ⚠ THE CENTRAL COELIAC FACT, AND IT IS NOT ON THE MENU: 藪 is one of the three classical Edo soba houses and hand-cut 蕎麦 in that tradition is 二八 — conventionally 20% WHEAT flour as the binder — and even a 十割 shop dusts its cutting board with 打ち粉 and boils in shared water. This shop declares nothing about its flour ratio, so every soba row here is "no", not "ask". ⚠ THE ENGLISH LOCALE COLLAPSES TWO DIFFERENT DISHES INTO ONE NAME: rows 8 and 9 are BOTH rendered "Tempura Soba" at the same ¥2,000, and only the Korean and Thai columns separate them — 텐자루 / เทนซุรุ is 天ざる, COLD soba with tempura on the side, while 튀김 소바 / โซบะเทมปุระ is 天ぷらそば, the HOT bowl. A diner ordering in English cannot tell which one they are pointing at. ⚠ 花巻 IS NOT BREAD. English calls row 5 "Flower Buns" and the Chinese locale writes 花捲, the steamed Chinese roll — but the Thai and Korean both transliterate it, ฮานามากิ / 화마키, so the dish is 花巻: hot soba under a drift of toasted nori. Nothing is baked and nothing is a bun. ⚠ AND ROW 3 IS NOT A RICE BOWL: the simplified-Chinese locale guesses 海苔盖饭 (a nori DONBURI) where Thai gives นอร์ริคาเกะ = のりかけ, more soba with nori. ⚠ THE ONE ROW WORTH KNOWING ABOUT IS 鴨ぬき. It is priced identically to 鴨南蛮 (¥2,100) and carries the same November–March window, and the Korean renders it 오리 뺀 — literally "duck, removed" — because ぬき at an Edo soba counter means the bowl served WITHOUT the soba: duck, grilled negi and hot broth, no noodles. It does not make the dish gluten-free, because the かえし that seasons the broth is soy sauce, but it is the only line here where the wheat noodle is optional by design rather than by request.',
  last_checked: T,
  items: [
    { ja: 'ざるそば', romaji: 'zaru soba', en: 'Cold soba with dipping sauce', price: '850円', section: 'Soba', gf: 'no', vegan: 'no',
      note: 'Hand-cut soba at a 藪 house is conventionally 二八 — 20% wheat — and the shop publishes no ratio. The つゆ is かえし (soy sauce) plus katsuo dashi, so it is wheat and fish at once.', dish_key: 'zaru_soba' },
    { ja: 'かけそば', romaji: 'kake soba', en: 'Hot soba in broth', price: '850円', section: 'Soba', gf: 'no', vegan: 'no',
      note: 'The plainest bowl on the menu and still both wheat and fish: undeclared 二八 noodles in a dashi-and-soy broth.', dish_key: 'kake_soba' },
    { ja: 'のりかけ', romaji: 'norikake', en: 'Soba with nori', price: '1,100円', section: 'Soba', gf: 'no', vegan: 'no',
      note: '⚠ The simplified-Chinese locale renders this 海苔盖饭, a nori RICE BOWL; the Thai transliteration นอร์ริคาเกะ shows it is のりかけ — soba, not rice. Wheat-bound noodles in dashi broth.', dish_key: 'norikake' },
    { ja: '山かけ', romaji: 'yamakake', en: 'Soba with grated yam', price: '1,200円', section: 'Soba', gf: 'no', vegan: 'no',
      note: 'Grated 山芋 over soba. The yam itself is plant and grain-free; the noodles and the dashi-soy つゆ are neither.', dish_key: 'yamakake' },
    { ja: '花巻', romaji: 'hanamaki', en: 'Hot soba under toasted nori', price: '1,100円', section: 'Soba', gf: 'no', vegan: 'no',
      note: '⚠ English says "Flower Buns" and the Chinese locale writes 花捲, the steamed roll. Thai ฮานามากิ and Korean 화마키 both transliterate it instead: this is 花巻, hot soba covered in toasted nori. No bread is involved. Still wheat noodles in a fish broth.', dish_key: 'hanamaki' },
    { ja: '玉子とじ', romaji: 'tamago-toji', en: 'Soba with egg dropped through the broth', price: '1,100円', section: 'Soba', gf: 'no', vegan: 'no',
      note: 'The Chinese 蛋花煮 (egg-flower simmer) identifies it as 玉子とじ, not the 玉子豆腐 the English "Egg Tofu" suggests. Egg, wheat noodles and dashi.', dish_key: 'tamago_toji' },
    { ja: 'おかめ', romaji: 'okame', en: 'Okame soba', price: '1,100円', section: 'Soba', gf: 'no', vegan: 'no',
      note: 'The traditional-Chinese locale leaves this in Japanese — おかめ — because there is no equivalent term. The shop publishes no composition, so what sits on top is unknown here; the noodles and broth alone are already wheat and fish.', dish_key: 'okame_soba' },
    { ja: '天ざる', romaji: 'tenzaru', en: 'Cold soba with tempura on the side', price: '2,000円', section: 'Soba', gf: 'no', vegan: 'no',
      note: '⚠ English calls this "Tempura Soba" and calls the NEXT row the same thing. Korean 텐자루 and Thai เทนซุรุ identify this one as 天ざる: the COLD plate, noodles dipped, tempura separate. Wheat twice over — the noodles and the batter.', dish_key: 'tenzaru' },
    { ja: '天ぷらそば', romaji: 'tempura soba', en: 'Hot soba with tempura in the bowl', price: '2,000円', section: 'Soba', gf: 'no', vegan: 'no',
      note: '⚠ Same English gloss and same price as 天ざる above; Korean 튀김 소바 and Thai โซบะเทมปุระ mark this as the HOT bowl with the tempura sitting in the broth. Wheat noodles, wheat batter, dashi.', dish_key: 'tempura_soba' },
    { ja: '鴨南蛮', romaji: 'kamo nanban', en: 'Hot duck and negi soba (November–March only)', price: '2,100円', section: 'Soba', gf: 'no', vegan: 'no',
      note: 'The traditional-Chinese locale preserves the shop’s own parenthetical 提供期間：11月～3月 — this is a winter dish and is simply absent for most of the year. Duck, grilled negi, soy-seasoned broth, wheat-bound noodles.', dish_key: 'kamo_nanban' },
    { ja: '板わさ', romaji: 'itawasa', en: 'Sliced kamaboko with wasabi', price: '850円', section: 'Side dishes', gf: 'no', vegan: 'no',
      note: 'The traditional-Chinese locale leaves it as 板わさ. Kamaboko is a fish paste bound with starch and eaten here with soy and wasabi; soy sauce is wheat unless a shop says tamari, and this one says nothing.', dish_key: 'itawasa' },
    { ja: '山葵芋', romaji: 'wasabi-imo', en: 'Wasabi-dressed yam', price: '850円', section: 'Side dishes', gf: 'ask', vegan: 'ask',
      note: '⚠ The four locales disagree about which tuber: English "Wasabi Potato", Chinese 山葵芋, Korean 와사비 고구마 (SWEET potato), Thai มันหวานวาซาบิ (also sweet potato). The shop publishes no description. Whichever it is, the risk is not the vegetable but what dresses it — a soba house seasons with かえし (soy) and often 出汁, which would make it neither gluten-free nor vegan. Ask.', dish_key: 'wasabi_imo' },
    { ja: '焼海苔', romaji: 'yaki-nori', en: 'Toasted nori', price: '850円', section: 'Side dishes', gf: 'ask', vegan: 'vegan',
      note: '⚠ The best row here for a plant-eater: toasted nori is seaweed and nothing else, so it is fully vegan in a building where every other line is fish or wheat. It is also naturally grain-free — the only question is the soy served beside it, which at a soba counter is a wheat soy sauce by default. Ask for it plain and it is clean.', dish_key: 'yaki_nori' },
    { ja: '天ぷら', romaji: 'tempura', en: 'Tempura', price: '1,700円', section: 'Side dishes', gf: 'no', vegan: 'ask',
      note: 'Tempura batter is wheat flour, and at a soba house it is conventionally loosened with egg — but the shop does not publish what is fried or what binds the batter, so the vegan answer is genuinely unknown rather than no. The wheat is not in doubt.', dish_key: 'tempura' },
    { ja: '鴨ぬき', romaji: 'kamo nuki', en: 'Duck and negi in broth, served without the soba (November–March only)', price: '2,100円', section: 'Side dishes', gf: 'no', vegan: 'no',
      note: '⚠ THE ONE ROW ON THIS MENU WHERE THE NOODLE IS OPTIONAL BY DESIGN. ぬき at an Edo soba counter means the bowl minus the soba, and the Korean locale gives it away by translating rather than transliterating: 오리 뺀, "duck, removed". Same ¥2,100 and the same 11月～3月 window as 鴨南蛮, which is the same dish with the noodles in it. It is still not gluten-free — the broth is seasoned with かえし, i.e. soy sauce — but a coeliac who wants what this shop actually does well has exactly one line to point at.', dish_key: 'kamo_nuki' },
  ],
});

put('s32', 'tokyo_mendokoro_takekawa', {
  verified: 'partial',
  confidence: 'medium',
  sources: [TB('A1303/A130301/13178370')],
  price_note:
    '12 rows in three named sections, read off Tabelog in four locales. 東京都渋谷区円山町7-2 (Maruyamacho, behind Shibuya), 22 seats, lunch only — 11:30–14:30, L.O. 14:00, Wednesday to Sunday, closed Monday and Tuesday. Average spend ¥1,000–1,999. ⚠ THE WORD THE WHOLE MENU TURNS ON IS 無添加, "ADDITIVE-FREE", and it is a claim about SEASONING, NOT ABOUT GLUTEN. Eight of the twelve rows carry it. A shop that has gone to the trouble of removing MSG and chemical seasonings reads, to an English-speaking coeliac, like a shop that is careful about ingredients in general — and it may well be — but tsukemen and ramen noodles are wheat, the かえし is soy sauce, and 無添加 changes neither. Nothing on this menu is gluten-free and nothing is vegan. ⚠ THE SECOND TRAP IS THE WORD そば. Rows 9–12 are 無添加そば 竹川クラシック, and the Chinese locale renders them 無添加蕎麥 while the Korean says 메밀국수 — BUCKWHEAT NOODLES, in both cases. They are not. At a ramen counter 中華そば/そば is the old Tokyo word for a WHEAT ramen noodle, which is why these rows sit under the section Tabelog labels "Ramen" and are priced ¥1,000–1,300 alongside the tsukemen. A buckwheat-seeking diner steered here by the Chinese or Korean page would be eating wheat. ⚠ THE STRUCTURE IS WORTH READING AS A GRID rather than twelve dishes: three base bowls (無添加つけめん ¥1,100, 竹川オリエンタル ¥1,250, 無添加そば ¥1,000) each sold four ways — plain, 味玉 (+¥150), チャーシュー (+¥200), 特製 (+¥300). Learn the four suffixes and the menu is three decisions, not twelve.',
  last_checked: T,
  items: [
    { ja: '無添加つけめん', romaji: 'mutenka tsukemen', en: 'Additive-free tsukemen', price: '1,100円', section: 'つけめん Dipping noodles', gf: 'no', vegan: 'no',
      note: '⚠ 無添加 is a claim about MSG and chemical seasoning, not about wheat. Tsukemen noodles are wheat and the dipping broth is soy-seasoned; this is the base price of the shop’s signature bowl.', dish_key: 'tsukemen' },
    { ja: '無添加つけめん 味玉', romaji: 'mutenka tsukemen ajitama', en: 'Additive-free tsukemen with seasoned egg', price: '1,250円', section: 'つけめん Dipping noodles', gf: 'no', vegan: 'no',
      note: '+¥150 over the plain bowl. 味玉 is an egg cured in a soy-and-mirin tare, so it adds a second wheat source as well as the egg.', dish_key: 'tsukemen_ajitama' },
    { ja: '無添加つけめん チャーシュー', romaji: 'mutenka tsukemen chāshū', en: 'Additive-free tsukemen with extra chashu', price: '1,300円', section: 'つけめん Dipping noodles', gf: 'no', vegan: 'no',
      note: '+¥200. Chashu is pork braised in soy sauce.', dish_key: 'tsukemen_chashu' },
    { ja: '無添加つけめん 特製', romaji: 'mutenka tsukemen tokusei', en: 'Additive-free tsukemen, special (all toppings)', price: '1,400円', section: 'つけめん Dipping noodles', gf: 'no', vegan: 'no',
      note: '+¥300, which is ¥50 less than buying the egg and the chashu separately. 特製 at a ramen counter conventionally means egg plus extra pork; the shop does not itemise it.', dish_key: 'tsukemen_tokusei' },
    { ja: '竹川オリエンタル', romaji: 'Takekawa Orientaru', en: 'Takekawa Oriental tsukemen', price: '1,250円', section: '竹川オリエンタルつけめん', gf: 'no', vegan: 'no',
      note: 'Its own section and its own base price, ¥150 above the plain tsukemen, but the shop publishes no description of what makes it "Oriental" — no spice, no broth, no ingredient is named anywhere on the page. Wheat noodles and a soy-seasoned dip are the only things that can be stated.', dish_key: 'takekawa_oriental' },
    { ja: '竹川オリエンタル 味玉', romaji: 'Takekawa Orientaru ajitama', en: 'Takekawa Oriental with seasoned egg', price: '1,400円', section: '竹川オリエンタルつけめん', gf: 'no', vegan: 'no',
      note: '+¥150. Soy-cured egg on an undescribed wheat-noodle bowl.', dish_key: 'takekawa_oriental_ajitama' },
    { ja: '竹川オリエンタル チャーシュー', romaji: 'Takekawa Orientaru chāshū', en: 'Takekawa Oriental with extra chashu', price: '1,450円', section: '竹川オリエンタルつけめん', gf: 'no', vegan: 'no',
      note: '+¥200. Pork braised in soy.', dish_key: 'takekawa_oriental_chashu' },
    { ja: '竹川オリエンタル 特製', romaji: 'Takekawa Orientaru tokusei', en: 'Takekawa Oriental, special', price: '1,550円', section: '竹川オリエンタルつけめん', gf: 'no', vegan: 'no',
      note: '+¥300 and the most expensive line in the shop. Contents not itemised.', dish_key: 'takekawa_oriental_tokusei' },
    { ja: '無添加そば 竹川クラシック', romaji: 'mutenka soba Takekawa kurashikku', en: 'Additive-free ramen, Takekawa Classic', price: '1,000円', section: 'ラーメン Ramen', gf: 'no', vegan: 'no',
      note: '⚠ そば HERE IS NOT BUCKWHEAT. The Chinese locale writes 無添加蕎麥 and the Korean 메밀국수 — both say buckwheat — but Tabelog files this row under Ramen, and at a ramen counter そば is the old Tokyo name for a WHEAT alkaline noodle. Anyone who came looking for soba because of the translation would be eating wheat. The cheapest bowl in the shop.', dish_key: 'soba_classic' },
    { ja: '無添加そば 竹川クラシック 味玉', romaji: 'mutenka soba Takekawa kurashikku ajitama', en: 'Takekawa Classic ramen with seasoned egg', price: '1,150円', section: 'ラーメン Ramen', gf: 'no', vegan: 'no',
      note: '+¥150. Wheat noodle despite the そば in the name; soy-cured egg.', dish_key: 'soba_classic_ajitama' },
    { ja: '無添加そば 竹川クラシック チャーシュー', romaji: 'mutenka soba Takekawa kurashikku chāshū', en: 'Takekawa Classic ramen with extra chashu', price: '1,200円', section: 'ラーメン Ramen', gf: 'no', vegan: 'no',
      note: '+¥200. Soy-braised pork.', dish_key: 'soba_classic_chashu' },
    { ja: '無添加そば 竹川クラシック 特製', romaji: 'mutenka soba Takekawa kurashikku tokusei', en: 'Takekawa Classic ramen, special', price: '1,300円', section: 'ラーメン Ramen', gf: 'no', vegan: 'no',
      note: '+¥300. Contents not itemised by the shop.', dish_key: 'soba_classic_tokusei' },
  ],
});

put('s20', 'tokyo_ramen_koku', {
  verified: 'partial',
  confidence: 'medium',
  sources: [TB('A1303/A130301/13149719')],
  price_note:
    '16 rows across four sections, read off Tabelog in four locales. 東京都渋谷区桜丘町29-5 石島ビル1F, nine counter seats, LUNCH ONLY — 12:00–15:00, Monday to Friday, closed weekends and public holidays. Average spend under ¥999, which for central Shibuya is unusual and is the point of the shop. Tabelog carries no telephone number: the listing prints 不明の為情報お待ちしております in place of one. ⚠ THE SHOP IS A WONTON SPECIALIST, AND THAT IS A GLUTEN FACT, NOT A STYLE NOTE. Six of the sixteen rows are 雲呑 — the wonton is sold in threes and fives inside the noodle bowls, five as a topping, and on its own as 皿雲呑. A wonton wrapper is wheat dough, so the item this shop is known for is the one a coeliac must refuse, and refusing it does not help: the noodles underneath are wheat too. ⚠ WHAT A COELIAC CAN ACTUALLY BUY HERE IS ¥50 OF RICE. 半ライス ¥50 and ライス ¥100 are the only two rows on the menu with no wheat in them by construction, and they are the cheapest lines in the shop. カレーライス at ¥280 is NOT a third option: Japanese curry roux is a flour-and-fat roux and is one of the most reliable hidden-wheat dishes in the country. ⚠ AND 担担麺 IS NOT A VEGETARIAN ESCAPE. It reads as a sesame-and-chilli noodle and is conventionally built on minced pork and a soy-based tare; the shop publishes no composition, so it is "ask" on vegan and a flat no on gluten. Toppings are ¥100–200 and the only plant one, 葱 at ¥100, is also the only one a vegan could add.',
  last_checked: T,
  items: [
    { ja: '醤油らーめん', romaji: 'shōyu rāmen', en: 'Soy sauce ramen', price: '750円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: 'The base bowl and the cheapest noodle in the shop. Wheat alkaline noodles in a soy-sauce broth — soy sauce is wheat-brewed unless a shop names tamari, and the broth at a wonton counter is animal stock.', dish_key: 'shoyu_ramen' },
    { ja: '【人気】醤油雲呑麺（3個）', romaji: 'shōyu wantanmen (san-ko)', en: 'Soy sauce wonton noodles, 3 wontons', price: '880円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: 'Marked 人気 (popular) by the shop. ⚠ A wonton wrapper is WHEAT DOUGH, so the house speciality doubles the wheat already in the bowl. +¥130 over the plain shoyu bowl for three.', dish_key: 'shoyu_wantanmen_3' },
    { ja: '【人気】醤油雲呑麺（5個）', romaji: 'shōyu wantanmen (go-ko)', en: 'Soy sauce wonton noodles, 5 wontons', price: '950円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: 'Two extra wontons for ¥70 — cheaper per piece than the three-wonton bowl. Wheat wrappers on wheat noodles.', dish_key: 'shoyu_wantanmen_5' },
    { ja: '塩らーめん', romaji: 'shio rāmen', en: 'Salt ramen', price: '770円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: '⚠ 塩 ramen looks like the safer choice because the name says salt rather than soy — it is not. The tare is lighter but the NOODLE is still wheat, and shio tare routinely contains soy or fish products anyway. ¥20 more than the shoyu.', dish_key: 'shio_ramen' },
    { ja: '塩雲呑麺（3個）', romaji: 'shio wantanmen (san-ko)', en: 'Salt wonton noodles, 3 wontons', price: '900円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: 'Wheat wrappers, wheat noodles, animal stock.', dish_key: 'shio_wantanmen_3' },
    { ja: '塩雲呑麺（5個）', romaji: 'shio wantanmen (go-ko)', en: 'Salt wonton noodles, 5 wontons', price: '970円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: 'The most expensive noodle bowl on the menu, and still under ¥1,000.', dish_key: 'shio_wantanmen_5' },
    { ja: '担担麺', romaji: 'tantanmen', en: 'Tantanmen', price: '880円', section: '麺類 Noodles', gf: 'no', vegan: 'ask',
      note: '⚠ Reads as a sesame-and-chilli noodle and is conventionally built on MINCED PORK with a soy-based tare — but this shop publishes no composition, so vegan is genuinely unknown rather than no. The wheat noodle is not in doubt.', dish_key: 'tantanmen' },
    { ja: '麺大盛', romaji: 'men ōmori', en: 'Large portion of noodles', price: '100円', section: '麺類 Noodles', gf: 'no', vegan: 'no',
      note: 'An upcharge, not a dish: ¥100 for more wheat noodles.', dish_key: 'men_omori' },
    { ja: '味付玉子', romaji: 'ajitsuke tamago', en: 'Seasoned egg', price: '100円', section: 'トッピング Toppings', gf: 'no', vegan: 'no',
      note: 'Egg cured in a soy-and-mirin tare — the curing liquid is the wheat, not the egg.', dish_key: 'ajitama' },
    { ja: 'メンマ', romaji: 'menma', en: 'Menma bamboo shoots', price: '150円', section: 'トッピング Toppings', gf: 'ask', vegan: 'ask',
      note: 'Fermented bamboo shoot is a plant, but menma is almost always seasoned in a soy-and-dashi liquor, which would make it both wheat and fish. The shop does not say. Ask.', dish_key: 'menma' },
    { ja: '葱', romaji: 'negi', en: 'Spring onion', price: '100円', section: 'トッピング Toppings', gf: 'gf', vegan: 'vegan',
      note: '⚠ The only unambiguously clean row on the whole menu: raw sliced negi, ¥100, nothing added. It is also the only topping a vegan can put on anything here — which matters mainly as a measure of how little this counter can offer.', dish_key: 'negi' },
    { ja: '雲呑（5個）', romaji: 'wantan (go-ko)', en: 'Wontons, 5 pieces as a topping', price: '200円', section: 'トッピング Toppings', gf: 'no', vegan: 'no',
      note: '¥200 to add five wontons — the same five that cost ¥70 when bought as part of the 5-piece bowl upgrade. Wheat wrappers.', dish_key: 'wantan_topping' },
    { ja: '半ライス', romaji: 'han raisu', en: 'Half portion of rice', price: '50円', section: 'ご飯もの Rice', gf: 'gf', vegan: 'vegan',
      note: '⚠ ¥50, and one of only two rows in the shop with no wheat in it by construction. Plain steamed rice, nothing on it.', dish_key: 'han_raisu' },
    { ja: 'ライス', romaji: 'raisu', en: 'Rice', price: '100円', section: 'ご飯もの Rice', gf: 'gf', vegan: 'vegan',
      note: 'Plain steamed rice. The full portion of the row above.', dish_key: 'raisu' },
    { ja: 'カレーライス', romaji: 'karē raisu', en: 'Curry rice', price: '280円', section: 'ご飯もの Rice', gf: 'no', vegan: 'ask',
      note: '⚠ NOT A THIRD RICE OPTION FOR A COELIAC. Japanese curry is thickened with a roux of WHEAT FLOUR cooked in fat — it is one of the most reliable hidden-wheat dishes in the country, and the word "rice" in the English name is what makes it dangerous. The meat content is not published, so vegan is unknown.', dish_key: 'curry_rice' },
    { ja: '皿雲呑', romaji: 'sara wantan', en: 'Wontons on a plate', price: '400円', section: '一品 Snacks', gf: 'no', vegan: 'no',
      note: 'The house speciality sold on its own without noodles — which removes one wheat source and leaves the other, since the wrapper is the wheat. The Thai locale mislabels these เกี๊ยวซ่า (gyoza); the Chinese 盤餛飩 has it right.', dish_key: 'sara_wantan' },
  ],
});

put('s32', 'tokyo_toomiya_tomiya', {
  verified: 'partial',
  confidence: 'medium',
  sources: [TB('A1304/A130401/13011949')],
  price_note:
    '30 rows read off Tabelog in four locales. 東京都新宿区西新宿1-19-2 セイコービル1F, 15 counter seats, 10:30–22:00, OPEN EVERY DAY OF THE YEAR, average spend under ¥999. A miso-ramen specialist — Tabelog files the shop as 味噌ラーメン専門店 and the JSON-LD names it "Miso Ramen Toomiya Shinjuku". ⚠ MISO IS THE REASON THIS RECORD MATTERS, AND NOT FOR THE REASON MOST PEOPLE EXPECT. 麦味噌 is BARLEY miso, and barley is NOT on Japan’s statutory allergen list, so a shop is under no obligation to declare it anywhere — not on the menu, not on an allergen chart, not when asked in English. A specialist that sells four different miso bases (赤 / 白 / 合わせ / 辛) has four different chances of one of them being barley-fermented, and this shop declares none of them. For a coeliac the noodle already settles the question, but anyone eating gluten-free BEYOND the noodle — ordering toppings, or the chashu rice bowl — needs to know that the miso itself is an open question here. ⚠ THE MENU IS A GRID, NOT THIRTY DISHES: four bases (辛味噌 ¥900, 赤味噌 ¥850, 白味噌 ¥850, 合わせ味噌 ¥900) each sold four ways — plain, 味玉 (+¥100), チャーシュー (+¥300), バターコーン (+¥300) — plus a 特選 version of each at ¥1,150–1,200. Nineteen of the thirty rows are that grid. ⚠ ONE ROW DEFEATS ALL FOUR LOCALES: row 14 at ¥1,150 comes out as "Special Shiro Miiso" in English, 特選白見磯 in Chinese, 흰바다 ("white sea") in Korean and ซาชิมิพิเศษ ("special SASHIMI") in Thai. Its price and its position — directly above the three 白味噌 rows, matching 特選赤味噌 at ¥1,150 and 特選辛味噌 at ¥1,200 — make it 特選白味噌, and the English is the only locale that got close. It is recorded as that, and the disagreement is recorded with it. ⚠ NOTHING ON THIS MENU IS GLUTEN-FREE. Rice at ¥150 and half rice at ¥100 are plain, and the chashu bowl on top of them is not.',
  last_checked: T,
  items: [
    { ja: '新商品 十味やの混ぜそば', romaji: 'shinshōhin Tōmiya no mazesoba', en: 'New: Toomiya’s mazesoba', price: '1,000円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Flagged 新商品 (new) by the shop. 混ぜそば is a brothless bowl — wheat noodles tossed with a concentrated tare, which is soy-based and usually carries pork fat. The absence of soup does not remove the wheat; it concentrates the seasoning.', dish_key: 'mazesoba' },
    { ja: '混ぜそば 推奨トッピング', romaji: 'mazesoba suishō toppingu', en: 'Recommended toppings for the mazesoba', price: '', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'A heading row with NO PRICE PRINTED and no contents listed — the shop points at recommended toppings without naming or pricing them. Recorded as it appears rather than guessed at.', dish_key: 'mazesoba_toppings' },
    { ja: '味噌つけ麺', romaji: 'miso tsukemen', en: 'Miso tsukemen', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Wheat noodles served cold with a concentrated miso dipping broth. ⚠ Which miso is not stated, and 麦味噌 is barley.', dish_key: 'miso_tsukemen' },
    { ja: '特選辛味噌', romaji: 'tokusen kara-miso', en: 'Premium spicy miso ramen', price: '1,200円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'The 特選 tier of the spicy base — ¥300 over the plain 辛味噌ラーメン. The shop does not itemise what 特選 adds.', dish_key: 'tokusen_karamiso' },
    { ja: '辛味噌ラーメン', romaji: 'kara-miso rāmen', en: 'Spicy miso ramen', price: '900円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Base price of the spicy miso bowl. Wheat noodles; the miso base is undeclared and may be barley-fermented.', dish_key: 'karamiso_ramen' },
    { ja: '辛味噌味玉ラーメン', romaji: 'kara-miso ajitama rāmen', en: 'Spicy miso ramen with seasoned egg', price: '1,000円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥100 for a soy-cured egg.', dish_key: 'karamiso_ajitama' },
    { ja: '辛味噌チャーシューラーメン', romaji: 'kara-miso chāshū rāmen', en: 'Spicy miso ramen with extra chashu', price: '1,200円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥300 for soy-braised pork.', dish_key: 'karamiso_chashu' },
    { ja: '辛味噌バターコーンラーメン', romaji: 'kara-miso batā kōn rāmen', en: 'Spicy miso ramen with butter and corn', price: '1,200円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '⚠ The Sapporo-style topping, and a DAIRY row — butter, on a bowl a vegetarian might otherwise have been weighing up. +¥300.', dish_key: 'karamiso_butter_corn' },
    { ja: '特選赤味噌', romaji: 'tokusen aka-miso', en: 'Premium red miso ramen', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '特選 tier of the red base, ¥300 over plain.', dish_key: 'tokusen_akamiso' },
    { ja: '赤味噌ラーメン', romaji: 'aka-miso rāmen', en: 'Red miso ramen', price: '850円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'One of the two cheapest bowls in the shop. 赤味噌 is conventionally a long-aged soybean miso, but the koji grain is not declared and barley miso is not a labelled allergen in Japan.', dish_key: 'akamiso_ramen' },
    { ja: '赤味噌味玉ラーメン', romaji: 'aka-miso ajitama rāmen', en: 'Red miso ramen with seasoned egg', price: '950円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥100.', dish_key: 'akamiso_ajitama' },
    { ja: '赤味噌チャーシューラーメン', romaji: 'aka-miso chāshū rāmen', en: 'Red miso ramen with extra chashu', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥300. Pork braised in soy.', dish_key: 'akamiso_chashu' },
    { ja: '赤味噌バターコーンラーメン', romaji: 'aka-miso batā kōn rāmen', en: 'Red miso ramen with butter and corn', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Dairy. +¥300.', dish_key: 'akamiso_butter_corn' },
    { ja: '特選白味噌', romaji: 'tokusen shiro-miso', en: 'Premium white miso ramen', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '⚠ THE ROW THAT DEFEATS EVERY LOCALE: English "Special Shiro Miiso", Chinese 特選白見磯, Korean 흰바다 ("white sea"), Thai ซาชิมิพิเศษ ("special sashimi"). Its ¥1,150 matches 特選赤味噌 exactly and it sits directly above the three 白味噌 rows, so it is the 特選 tier of the white base. Recorded as 特選白味噌 with the disagreement stated rather than hidden. ⚠ 白味噌 is normally a sweet RICE-koji miso, which is the one variety least likely to be barley — but this shop declares nothing.', dish_key: 'tokusen_shiromiso' },
    { ja: '白味噌ラーメン', romaji: 'shiro-miso rāmen', en: 'White miso ramen', price: '850円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Joint cheapest bowl with the red. Wheat noodles in an undeclared miso base.', dish_key: 'shiromiso_ramen' },
    { ja: '白味噌味玉ラーメン', romaji: 'shiro-miso ajitama rāmen', en: 'White miso ramen with seasoned egg', price: '950円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥100.', dish_key: 'shiromiso_ajitama' },
    { ja: '白味噌チャーシューラーメン', romaji: 'shiro-miso chāshū rāmen', en: 'White miso ramen with extra chashu', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥300.', dish_key: 'shiromiso_chashu' },
    { ja: '白味噌バターコーンラーメン', romaji: 'shiro-miso batā kōn rāmen', en: 'White miso ramen with butter and corn', price: '1,150円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Dairy. +¥300.', dish_key: 'shiromiso_butter_corn' },
    { ja: '特選合わせ味噌', romaji: 'tokusen awase-miso', en: 'Premium blended miso ramen', price: '1,200円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '⚠ 合わせ味噌 means two or more misos BLENDED, which is the worst case for anyone tracking barley: it doubles the number of undeclared koji grains in one bowl. The Chinese locale gives up entirely and renders it 特選合併, "premium merger".', dish_key: 'tokusen_awasemiso' },
    { ja: '合わせ味噌ラーメン', romaji: 'awase-miso rāmen', en: 'Blended miso ramen', price: '900円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Two or more misos blended; neither is named.', dish_key: 'awasemiso_ramen' },
    { ja: '合わせ味噌味玉ラーメン', romaji: 'awase-miso ajitama rāmen', en: 'Blended miso ramen with seasoned egg', price: '1,000円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥100.', dish_key: 'awasemiso_ajitama' },
    { ja: '合わせ味噌チャーシューラーメン', romaji: 'awase-miso chāshū rāmen', en: 'Blended miso ramen with extra chashu', price: '1,200円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: '+¥300.', dish_key: 'awasemiso_chashu' },
    { ja: '合わせ味噌バターコーンラーメン', romaji: 'awase-miso batā kōn rāmen', en: 'Blended miso ramen with butter and corn', price: '1,200円', section: 'メニュー Menu', gf: 'no', vegan: 'no',
      note: 'Dairy. +¥300.', dish_key: 'awasemiso_butter_corn' },
    { ja: '味玉', romaji: 'ajitama', en: 'Seasoned soft-boiled egg', price: '100円', section: 'トッピング Toppings', gf: 'no', vegan: 'no',
      note: 'Cured in a soy-and-mirin tare. The wheat is in the curing liquid.', dish_key: 'ajitama' },
    { ja: 'チャーシュー', romaji: 'chāshū', en: 'Chashu pork', price: '300円', section: 'トッピング Toppings', gf: 'no', vegan: 'no',
      note: 'Pork braised in soy sauce.', dish_key: 'chashu' },
    { ja: '海苔増量', romaji: 'nori zōryō', en: 'Extra nori', price: '150円', section: 'トッピング Toppings', gf: 'ask', vegan: 'vegan',
      note: 'Sheet nori is seaweed and nothing else — the only vegan topping on the board. Plain nori carries no grain, though sheets sold to ramen shops are sometimes seasoned; on its own it is as clean as this menu gets.', dish_key: 'nori' },
    { ja: 'メンマ', romaji: 'menma', en: 'Menma bamboo shoots', price: '150円', section: 'トッピング Toppings', gf: 'ask', vegan: 'ask',
      note: 'Fermented bamboo, but seasoned — conventionally in soy and dashi, which would make it both wheat and fish. Not declared.', dish_key: 'menma' },
    { ja: 'ライス(150g)', romaji: 'raisu', en: 'Rice, 150g', price: '150円', section: 'ご飯もの Rice', gf: 'gf', vegan: 'vegan',
      note: 'Plain steamed rice, portion stated by the shop. One of the two clean rows on the menu.', dish_key: 'raisu' },
    { ja: '半ライス(100g)', romaji: 'han raisu', en: 'Half rice, 100g', price: '100円', section: 'ご飯もの Rice', gf: 'gf', vegan: 'vegan',
      note: 'Plain steamed rice, 100g. ¥50 less than the full portion for 50g less.', dish_key: 'han_raisu' },
    { ja: 'チャーシュー丼', romaji: 'chāshū-don', en: 'Chashu rice bowl', price: '400円', section: 'ご飯もの Rice', gf: 'no', vegan: 'no',
      note: '⚠ Rice is the clean part and the pork on top is not: chashu is braised in soy sauce and the bowl is finished with the same tare. A rice dish is not automatically the gluten-free choice.', dish_key: 'chashu_don' },
  ],
});

console.log('batch 1 done');
