// Local tick 2026-09-10, batch 2.
import { put, T } from './_tick_lib.mjs';

const TB = u => `https://tabelog.com/en/tokyo/${u}/dtlmenu/`;

put('s31', 'tokyo_sushi_bigin', {
  verified: 'partial',
  confidence: 'low',
  sources: [TB('A1310/A131003/13313866')],
  price_note:
    'A 12-row 季節のにぎり list read off Tabelog in four locales, WITH NO PRICE ON A SINGLE ROW. 東京都千代田区神田神保町1-16-1, SEVEN counter seats, 18:00–22:00, Tuesday to Saturday, closed Sunday and Monday; the listing takes online reservations. Average spend ¥20,000–29,999 — the most expensive record in the Tokyo set so far, and the reason confidence is "low" rather than "medium": what is published here is a list of NETA, not a menu. There is no course price, no per-piece price and no omakase price anywhere on the page, and only seven reviews behind the ¥20–30k figure. ⚠ WHAT A COELIAC NEEDS TO KNOW ABOUT A COUNTER LIKE THIS IS NOT ON THE LIST. Edo-style nigiri is brushed at the counter with 煮切り — soy sauce reduced with sake and mirin — so the sushi arrives ALREADY SAUCED and there is no dish of soy to decline. Rice, fish and vinegar are all naturally gluten-free; the brush is not, and neither is 漬け, which is a soy MARINADE and appears explicitly on this list. At ¥20,000+ a seat, an omakase counter is also exactly the kind of room where asking in advance works — which is the practical advice, not "avoid". ⚠ THE ENGLISH LOCALE MISNAMES AT LEAST TWO FISH. Row 2 is glossed "Surf Clam", but Chinese keeps the kanji 平貝 — TAIRAGI, a pen shell, a completely different animal from the 北寄貝/青柳 that "surf clam" means, and Thai guesses หอยเป๋าฮื้อ, ABALONE. Row 7 is glossed "Shima Aji" (striped jack) while all three other locales say KOHADA — 小肌魚 / 작은 고등어 / ปลาขนาดเล็ก — gizzard shad, which is what row 1’s 新子 is the juvenile of. Both are recorded with the disagreement stated rather than resolved by guessing. ⚠ THE LIST IS SEASONAL AND THE SEASONS CONTRADICT EACH OTHER: 新子 is a high-summer neta (July–September), 香箱蟹 is legal only from early November to late December, and 春子 is a spring fish. No diner sees all twelve. It is a catalogue of what the shop buys across a year, not what is on the counter tonight.',
  last_checked: T,
  items: [
    { ja: '新子', romaji: 'shinko', en: 'Shinko — juvenile gizzard shad', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'The baby of the kohada, cured in salt and vinegar and famously the most labour-intensive neta in Edo sushi — several fish to one piece. Salt, vinegar and rice are all gluten-free; the 煮切り brushed on at the counter is soy sauce. No price published.', dish_key: 'shinko' },
    { ja: '平貝', romaji: 'tairagi', en: 'Pen shell', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: '⚠ English calls this "Surf Clam" and Thai calls it ABALONE; the Chinese locale preserves the kanji 平貝, which is tairagi — a PEN SHELL, not a surf clam and not an abalone. Three different animals under one row. The shellfish itself carries no grain; the brush does.', dish_key: 'tairagi' },
    { ja: '鯵', romaji: 'aji', en: 'Horse mackerel', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'Served with ginger and negi in the Edo manner. The Korean locale says 전어 (gizzard shad) and the Thai ปลาซาบะ (saba) — both wrong against the Chinese 鯵魚 and the English.', dish_key: 'aji' },
    { ja: '雲丹', romaji: 'uni', en: 'Sea urchin', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'Usually served 軍艦, wrapped in a nori band — nori is clean, the soy brush is not. Market-price neta with no figure published.', dish_key: 'uni' },
    { ja: '本鮪 中トロ', romaji: 'hon-maguro chūtoro', en: 'Bluefin chutoro', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'The medium-fatty cut. 本鮪 specifies BLUEFIN rather than any tuna, which the English "Bluefin Tuna Chutoro" carries correctly.', dish_key: 'chutoro' },
    { ja: '本鮪 漬け赤身', romaji: 'hon-maguro zuke akami', en: 'Soy-marinated bluefin akami', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'no', vegan: 'no',
      note: '⚠ THE ONE ROW ON THIS LIST THAT IS DEFINITELY NOT GLUTEN-FREE, AND IT IS NOT OBVIOUS IN ENGLISH. 漬け means steeped in SOY SAUCE — the gluten is not brushed on at the end, it is inside the fish. "Marinated" in the English gloss does not say in what.', dish_key: 'zuke_akami' },
    { ja: '小肌', romaji: 'kohada', en: 'Gizzard shad', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: '⚠ Locale conflict: English glosses this row "Shima Aji" (striped jack) while Chinese 小肌魚, Korean 작은 고등어 and Thai ปลาขนาดเล็ก all point at KOHADA, the grown fish of row 1’s 新子. Recorded as kohada, with the English disagreement noted. Salt- and vinegar-cured.', dish_key: 'kohada' },
    { ja: '本鮪 大トロ', romaji: 'hon-maguro ōtoro', en: 'Bluefin otoro', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'The fattiest belly cut and conventionally the most expensive neta on any counter — and, like everything here, unpriced.', dish_key: 'otoro' },
    { ja: '赤貝', romaji: 'akagai', en: 'Ark shell clam', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'Ark shell, scored and slapped on the board to make it curl. Shellfish allergen; no grain in the clam itself.', dish_key: 'akagai' },
    { ja: '春子（かすご）', romaji: 'kasugo', en: 'Kasugo — young sea bream', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: 'The Chinese locale preserves the shop’s own reading gloss 春子（かすご）. A juvenile 鯛, vinegar-cured; English "Spring Child" is a literal reading of the kanji and names no fish at all.', dish_key: 'kasugo' },
    { ja: '香箱蟹', romaji: 'kōbako-gani', en: 'Kobako crab — female snow crab', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'ask', vegan: 'no',
      note: '⚠ The narrowest season on the list: the female snow crab may legally be landed only from early November to late December, so this row exists for about seven weeks a year. Served for its inner and outer roe. Crustacean allergen.', dish_key: 'kobakogani' },
    { ja: 'シャリ', romaji: 'shari', en: 'Sushi rice', price: '', section: '季節のにぎり Seasonal nigiri', gf: 'gf', vegan: 'vegan',
      note: '⚠ The only row here that is not an animal, and the only one that can be called clean without a caveat: shari is rice, rice vinegar, salt and sugar. It appears on a seasonal NETA list because at a counter of this kind the rice is treated as an ingredient in its own right. Nothing in it is wheat — the wheat at a sushi counter arrives on the brush.', dish_key: 'shari' },
  ],
});

put('s34', 'tokyo_kushiyaki_ishikawa', {
  verified: 'partial',
  confidence: 'medium',
  sources: [TB('A1304/A130401/13123954')],
  price_note:
    '16 rows in four sections, read off Tabelog in four locales. 東京都新宿区西新宿7-12-23 松沢ビル2F, 16 seats (7 at the counter), 17:30–23:30 with food L.O. 22:30, Monday to Saturday, closed Sunday. Average spend ¥4,000–4,999. ⚠ THE FIRST TWO ROWS ARE PRICE BANDS, NOT DISHES, AND THAT IS THE MOST USEFUL THING ON THE PAGE. ¥200 buys any of むね (four flavours — わさび, 梅しそ, チーズ, 柚子胡椒), もも, ねぎま, つくね, かわ or 手羽; ¥180 buys any of レバー, せせり, 砂肝, ぼんじり, ハツ or なんこつ. Eleven or more skewers at two prices. They are recorded as the two rows the shop actually prints, because splitting them into twelve invented items would be inventing twelve prices the shop never published. ⚠ AND THE BAND HIDES THE ONE SKEWER A COELIAC MUST REFUSE: つくね is minced chicken BOUND — conventionally with flour, panko or starch — and it sits inside the ¥200 row next to plain もも, at the same price, with nothing to distinguish it. The shop does not say whether its skewers are grilled 塩 or タレ; タレ is a soy-sauce glaze and therefore wheat, and at a yakitori counter it is usually the default unless you ask for salt. ⚠ THE 〆 SECTION IS ENTIRELY WHEAT AND IS LABELLED "Rice Dishes". Of the four rows Tabelog files under rice, only 炒飯 and 雑炊 are actually rice; 玉うどん ¥550 and 温麺 ¥600 are noodles. A diner reading the English section heading and ordering blind from it has a one-in-two chance of being handed udon. ⚠ ONE ROW NAMES A DISH IN NO LANGUAGE: row 5, ¥200, comes out as "Honey Bread" / 麵包蜜 / 빵꿀 / ขนมปังมิตสึ — all four locales agree only that it is bread and honey, and none of them recovers the Japanese. It is filed as unresolved rather than invented. Whatever it is, bread is wheat and honey is not vegan.',
  last_checked: T,
  items: [
    { ja: 'むね（わさび・梅しそ・チーズ・柚子胡椒）・もも・ねぎま・つくね・かわ・手羽', romaji: 'mune (wasabi / ume-shiso / chīzu / yuzu-koshō), momo, negima, tsukune, kawa, teba', price: '200円', section: '焼き物 Grilled skewers', gf: 'ask', vegan: 'no',
      note: '⚠ A PRICE BAND, NOT A DISH — six or more different skewers all at ¥200, printed as one row. ⚠ つくね IS INSIDE IT: minced chicken is conventionally bound with flour, panko or starch, so the one skewer with a real wheat question sits at the same price as plain もも with nothing to mark it. チーズ is dairy. And the shop never states 塩 or タレ; タレ is a soy glaze, i.e. wheat, and is the default at most counters unless salt is requested. Ask for 塩 and ask about the つくね separately.', dish_key: 'yakitori_200' },
    { ja: 'レバー・せせり・砂肝・ぼんじり・ハツ・なんこつ', romaji: 'rebā, seseri, sunagimo, bonjiri, hatsu, nankotsu', price: '180円', section: '焼き物 Grilled skewers', gf: 'ask', vegan: 'no',
      note: 'The cheaper band: liver, neck, gizzard, tail, heart, cartilage — offal and off-cuts at ¥180. All are whole muscle or organ with no binder, so the only gluten question is the glaze: タレ is wheat, 塩 is not, and the shop does not say which it uses.', dish_key: 'yakitori_180' },
    { ja: '肉巻き野菜［豚バラで巻いた串］', romaji: 'nikumaki yasai', en: 'Vegetables wrapped in pork belly, skewered', price: '200円', section: '焼き物 Grilled skewers', gf: 'ask', vegan: 'no',
      note: '⚠ Filed under vegetables and it is a PORK dish — the shop’s own bracket says 豚バラで巻いた串, wrapped in pork belly. Which vegetables is not stated. The glaze question applies as above.', dish_key: 'nikumaki_yasai' },
    { ja: '野菜焼き', romaji: 'yasai-yaki', en: 'Grilled vegetables', price: '', section: '焼き物 Grilled skewers', gf: 'ask', vegan: 'ask',
      note: 'NO PRICE PRINTED and no vegetables named. The only row in the grilled section that could be vegan, and nothing on the page confirms it — a yakitori grill is shared with chicken fat and the glaze may be soy. Worth asking about; not worth assuming.', dish_key: 'yasai_yaki' },
    { ja: '(未確定 — bread and honey)', romaji: '(unresolved)', en: 'Bread with honey', price: '200円', section: '焼き物 Grilled skewers', gf: 'no', vegan: 'no',
      note: '⚠ THE JAPANESE NAME IS NOT RECOVERABLE FROM ANY OF THE FOUR LOCALES. English "Honey Bread", Chinese 麵包蜜, Korean 빵꿀, Thai ขนมปังมิตสึ — all four agree only on bread + honey, none preserves or transliterates the original. Recorded as unresolved rather than invented. Bread is wheat; honey is an animal product, so it is neither gluten-free nor vegan whatever it turns out to be called.', dish_key: 'honey_bread_unresolved' },
    { ja: '焼き盛り合わせ', romaji: 'yaki moriawase', en: 'Assorted grilled skewers', price: '', section: '焼き物 Grilled skewers', gf: 'ask', vegan: 'no',
      note: 'NO PRICE PRINTED, and no list of what is in it — which means an assortment could include the つくね from the ¥200 band without warning. Order the skewers individually if the binder matters.', dish_key: 'yaki_moriawase' },
    { ja: '茹でたてアスパラ', romaji: 'yudetate asupara', en: 'Freshly boiled asparagus', price: '500円', section: '一品 Dishes', gf: 'ask', vegan: 'ask',
      note: 'Asparagus, boiled to order. The vegetable is clean; what an izakaya puts on it — mayonnaise, butter, a soy dressing, bonito — is not published, and any of the four would change both answers.', dish_key: 'asupara' },
    { ja: '生キャベツ', romaji: 'nama kyabetsu', en: 'Raw cabbage', price: '350円', section: '一品 Dishes', gf: 'ask', vegan: 'ask',
      note: 'The cheapest plant on the menu. Raw cabbage is nothing but cabbage — the question is entirely the dip it comes with, which izakaya conventionally make from miso, sesame oil or mayonnaise and which this shop does not describe.', dish_key: 'nama_kyabetsu' },
    { ja: '漬物', romaji: 'tsukemono', en: 'Pickles', price: '350円', section: '一品 Dishes', gf: 'ask', vegan: 'ask',
      note: '⚠ Japanese pickles are a routine hidden-animal item: many are cured in a liquor containing DASHI, and a dashi note is a vegan fact and a gluten fact at once, because commercial 白だし and だし醤油 are soy-based. Which pickles is not stated.', dish_key: 'tsukemono' },
    { ja: 'たたみいわし', romaji: 'tatami-iwashi', en: 'Pressed dried whitebait sheet', price: '500円', section: '一品 Dishes', gf: 'ask', vegan: 'no',
      note: '⚠ Locale conflict on the name: Korean transliterates 다다미이와시 = tatami-iwashi, the pressed sheet of dried baby sardines, while Chinese renders 鳴門鰯 and Thai "crisp-fried mackerel". Recorded from the Korean, which is the only locale here that transliterates rather than translates. Either way it is whole small FISH — dried, lightly toasted, usually eaten with soy.', dish_key: 'tatami_iwashi' },
    { ja: '蒸し鶏冷菜', romaji: 'mushidori reisai', en: 'Chilled steamed chicken', price: '500円', section: '一品 Dishes', gf: 'ask', vegan: 'no',
      note: 'Steamed chicken served cold. The chicken is plain; the dressing on a 冷菜 is conventionally sesame and soy, which would be wheat, and is not described.', dish_key: 'mushidori' },
    { ja: '炒飯', romaji: 'chāhan', en: 'Fried rice', price: '500円', section: '〆 Rice and noodles', gf: 'no', vegan: 'no',
      note: 'Fried rice at a Japanese izakaya is seasoned with soy sauce and usually egg. Rice is not the issue; the seasoning is.', dish_key: 'chahan' },
    { ja: '玉うどん', romaji: 'tama udon', en: 'Udon', price: '550円', section: '〆 Rice and noodles', gf: 'no', vegan: 'no',
      note: '⚠ FILED UNDER "Rice Dishes" BY TABELOG AND IT IS WHEAT NOODLES. Udon is wheat flour, salt and water, and the broth is dashi and soy. Two of the four rows in this section are noodles, not rice.', dish_key: 'tama_udon' },
    { ja: '雑炊', romaji: 'zōsui', en: 'Rice simmered in broth', price: '600円', section: '〆 Rice and noodles', gf: 'no', vegan: 'no',
      note: 'Rice cooked down in the shop’s broth — which at a chicken counter means chicken stock seasoned with soy. The Korean locale mistranslates it 죽순, bamboo shoot.', dish_key: 'zosui' },
    { ja: '温麺', romaji: 'nyūmen / atatakai men', en: 'Hot noodles', price: '600円', section: '〆 Rice and noodles', gf: 'no', vegan: 'no',
      note: '⚠ The second noodle row hiding in the rice section, and the Thai locale reads it outright as udon. Whether it is 温麺 in the Sendai sense or simply a hot noodle bowl, both are WHEAT, in a dashi-and-soy broth.', dish_key: 'nyumen' },
    { ja: 'カタラーナ', romaji: 'katarāna', en: 'Catalana — frozen custard', price: '400円', section: 'デザート Dessert', gf: 'ask', vegan: 'no',
      note: 'The only dessert. A crema catalana served frozen: cream, egg yolk and sugar, so dairy and egg. The custard itself normally carries no flour, but nothing here is declared.', dish_key: 'catalana' },
  ],
});

put('s37', 'tokyo_sakadokoro_sakura', {
  verified: 'partial',
  confidence: 'low',
  sources: [TB('A1303/A130301/13084047')],
  price_note:
    '⚠ READ THE STATUS BEFORE THE MENU: TABELOG HAS THIS SHOP MARKED 掲載保留, "Listing on hold", with the red status badge and the explanatory line "The closure period for this restaurant is undetermined, or it may have relocated or permanently closed. The operational status is unconfirmed." That is Tabelog declining to vouch that the shop is trading — it is NOT a confirmed closure, and it is not entered as one in the place record, which stays a human’s call. The listing also carries no telephone number in its JSON-LD. Treat the 14 rows below as the last menu the shop published, not as tonight’s board, and confirm the shop exists before travelling. 東京都渋谷区宇田川町36-16 プラザマリーナ2F, 12 seats at a U-shaped counter, 17:30–23:30, closed Saturday and Sunday, average spend ¥3,000–3,999. ⚠ TWO ROWS ON THIS MENU ARE NAMED AFTER ANIMALS THAT ARE NOT IN THEM, AND BOTH FOOL ALL FOUR LOCALES. たぬき豆腐 comes out as "Tanuki Tofu" / 狸豆腐 / 너구리 두부 — raccoon-dog tofu — when たぬき in a Japanese kitchen is 天かす, the scraps of TEMPURA BATTER skimmed off the fryer. It is pure wheat, it is scattered on top, and it turns the one tofu dish on the menu into the one a coeliac must refuse. きつね餃子 comes out as "Fox Gyoza" / 狐狸餃子 / 여우 군만두: きつね means 油揚げ, deep-fried tofu, named for the fox because that is what foxes are said to eat. The dish is not fox and the tofu does not make it vegetarian — gyoza filling is conventionally pork, and the wrapper is wheat regardless. ⚠ THE THIRD TRAP RUNS THE OTHER WAY AND IS GOOD NEWS: 西京漬 on the two grilled-fish rows is a marinade of 西京味噌, which is a sweet WHITE miso fermented on RICE koji rather than barley — the one miso style with the least wheat exposure. It does not make the dish gluten-free (mirin and sake are in the marinade and nothing is declared) but it is the opposite of the usual miso problem. ⚠ AND THE PRICING IS WORTH A LOOK: 自家製特製ローストビーフ, described by the shop as 黒毛和牛A5, is ¥1,000 — the same as nothing else on the menu and remarkably little for an A5 claim. The shop names no producer and no certificate.',
  last_checked: T,
  items: [
    { ja: '女将おすすめ 日替わり小鉢', romaji: 'okami osusume higawari kobachi', en: 'Daily small dish, recommended by the landlady', price: '800円', section: '前菜 Appetiser', gf: 'ask', vegan: 'ask',
      note: 'Changes daily and is never described, so nothing about it can be stated in advance — including whether it is even plant-based. The one row on the menu where asking at the counter is the only method.', dish_key: 'higawari_kobachi' },
    { ja: '自家製玉子焼き', romaji: 'jikasei tamagoyaki', en: 'House-made tamagoyaki', price: '600円', section: '酒の肴 With a drink', gf: 'no', vegan: 'no',
      note: 'Egg, and not only egg: a Japanese rolled omelette is seasoned with DASHI and usually a splash of soy and mirin, so it carries fish and wheat as well. One of the most reliably misread "vegetarian" items in an izakaya.', dish_key: 'tamagoyaki' },
    { ja: 'おすすめ！ワンタンチーズ', romaji: 'wantan chīzu', en: 'Wonton cheese', price: '600円', section: '酒の肴 With a drink', gf: 'no', vegan: 'no',
      note: 'Marked おすすめ by the shop. Cheese in a wonton wrapper — the wrapper is WHEAT dough and the filling is dairy.', dish_key: 'wantan_cheese' },
    { ja: '豚の水煮', romaji: 'buta no mizuni', en: 'Boiled pork', price: '800円', section: 'お食事 Meal', gf: 'ask', vegan: 'no',
      note: 'Pork simmered in water — the meat itself is plain, and the whole gluten question is the sauce it is served with, which the shop does not name.', dish_key: 'buta_mizuni' },
    { ja: 'おすすめ！自家製特製ローストビーフ（黒毛和牛A5ランク）', romaji: 'jikasei tokusei rōsutobīfu (kuroge wagyū A5)', en: 'House roast beef, stated as A5 kuroge wagyu', price: '1,000円', section: 'お食事 Meal', gf: 'ask', vegan: 'no',
      note: '⚠ The shop’s own claim is 黒毛和牛A5ランク at ¥1,000, which is a great deal of grading for the money and names no producer, no farm and no certificate number. Recorded as the shop states it. For a coeliac the meat is not the risk — roast beef is served with a sauce, and a Japanese izakaya sauce is soy-based unless stated otherwise.', dish_key: 'roast_beef' },
    { ja: '唐揚げ', romaji: 'kara-age', en: 'Fried chicken', price: '800円', section: 'お食事 Meal', gf: 'no', vegan: 'no',
      note: 'Kara-age is marinated in SOY SAUCE and dredged in flour or starch before frying, then cooked in oil shared with everything else fried in the kitchen. Wheat at two stages.', dish_key: 'karaage' },
    { ja: '筑前煮', romaji: 'chikuzen-ni', en: 'Chikuzen-ni — simmered chicken and root vegetables', price: '800円', section: 'お食事 Meal', gf: 'no', vegan: 'no',
      note: '⚠ Reads as a vegetable dish and is a CHICKEN dish: lotus root, carrot, burdock and konnyaku simmered WITH chicken in soy sauce, mirin and dashi. Three separate reasons it is neither vegan nor gluten-free.', dish_key: 'chikuzen_ni' },
    { ja: 'たぬき豆腐', romaji: 'tanuki-dōfu', en: 'Tofu topped with tempura batter crumbs', price: '600円', section: 'お食事 Meal', gf: 'no', vegan: 'no',
      note: '⚠ THE SHARPEST TRAP ON THIS MENU. All four locales translate たぬき as the ANIMAL — "Tanuki Tofu", 狸豆腐, 너구리 두부, เต้าหู้ทานุกิ — but in a Japanese kitchen たぬき means 天かす: the crisp scraps of TEMPURA BATTER skimmed off the fryer. So the single tofu dish on the menu, the obvious choice for someone avoiding meat, is topped with pure wheat, and is also dressed with dashi-and-soy. Nothing in any of the four translations says the word flour.', dish_key: 'tanuki_dofu' },
    { ja: '焼き魚（銀鮭 西京漬）', romaji: 'yakizakana (ginzake saikyō-zuke)', en: 'Grilled coho salmon in white miso marinade', price: '800円', section: 'お食事 Meal', gf: 'ask', vegan: 'no',
      note: '⚠ Better news than miso usually is: 西京味噌 is a sweet WHITE miso fermented on RICE koji, not barley, so this is the miso style with the least hidden-wheat exposure — the opposite of the usual 麦味噌 problem. Not a clearance, though: the marinade also carries mirin and sake and the shop declares nothing.', dish_key: 'ginzake_saikyozuke' },
    { ja: '焼き魚（目抜け 西京漬）', romaji: 'yakizakana (menuke saikyō-zuke)', en: 'Grilled menuke rockfish in white miso marinade', price: '800円', section: 'お食事 Meal', gf: 'ask', vegan: 'no',
      note: 'The Chinese locale preserves the Japanese 目抜け 西京漬. メヌケ is a deep-water rockfish; same rice-koji miso marinade as the salmon row, same caveat.', dish_key: 'menuke_saikyozuke' },
    { ja: 'きつね餃子', romaji: 'kitsune gyōza', en: 'Kitsune gyoza', price: '800円', section: 'お食事 Meal', gf: 'no', vegan: 'no',
      note: '⚠ NOT FOX, AND NOT VEGETARIAN EITHER. All four locales read きつね as the animal — "Fox Gyoza", 狐狸餃子, 여우 군만두 — but きつね in Japanese cooking means 油揚げ, deep-fried tofu, named after the fox because of the folk belief about what foxes eat. Seeing "tofu" in the explanation does not help: gyoza filling is conventionally pork and the wrapper is wheat dough. The shop publishes no composition.', dish_key: 'kitsune_gyoza' },
    { ja: '鶏チャーシュー風', romaji: 'tori chāshū-fū', en: 'Chicken, chashu style', price: '700円', section: 'お食事 Meal', gf: 'no', vegan: 'no',
      note: 'チャーシュー風 means cooked in the manner of chashu — braised in SOY SAUCE, sugar and aromatics. The style is the wheat.', dish_key: 'tori_chashu' },
    { ja: 'お茶漬け', romaji: 'ochazuke', en: 'Ochazuke — rice in tea or broth', price: '600円', section: '〆のごはん Final rice', gf: 'no', vegan: 'no',
      note: '⚠ Rice in hot liquid, and the liquid is the problem: ochazuke is poured with dashi or a commercial 出汁の素, and the topping is conventionally salmon, cod roe or 昆布 seasoned with soy. Neither the broth nor the topping is declared.', dish_key: 'ochazuke' },
    { ja: 'ご飯セット（味噌汁・お新香付き）', romaji: 'gohan setto (misoshiru, oshinko tsuki)', en: 'Rice set with miso soup and pickles', price: '500円', section: '〆のごはん Final rice', gf: 'no', vegan: 'ask',
      note: '⚠ The cheapest row on the menu and three separate questions in one. The rice is clean; the MISO SOUP is built on dashi (fish) and on a miso whose koji grain is undeclared — 麦味噌 is barley and barley is not a labelled allergen in Japan; the お新香 are pickles, often cured with dashi. Vegan is genuinely unknown; gluten-free it is not.', dish_key: 'gohan_set' },
  ],
});

console.log('batch 2 done');
