// Local tick 2026-09-11 — real menus, part H: 洋食 林屋 (新宿).
// 82 harvested rows reduce to 56 distinct dishes: 19 are Tabelog CATEGORY PLACEHOLDERS
// (a row whose name equals its own section name and carries no price — "Pasta" in
// [Pasta], "Curry" in [Curry], "Sashimi" in [Sashimi]) and 7 are exact duplicates of
// rows printed earlier in the list. Both are recorded in the price_note rather than
// silently dropped.
import { put, T } from './_tick_lib.mjs';
const TB = u => `https://tabelog.com/en/tokyo/${u}/dtlmenu/`;

const ROUX =
  ' ⚠ ROUX: this sauce is built on wheat flour cooked in fat. It is the defining technique of 洋食 and it is not removable — the flour is the sauce, not a thickener added to it.';
const FRYER =
  ' Shared fryer: the same oil serves panko-crumbed cutlets, battered fish and croquettes all day.';

put('s36', 'tokyo_hayashiya_restaurant_hay', {
  verified: 'partial',
  confidence: 'medium',
  sources: [TB('A1304/A130401/13077952')],
  price_note:
    'Read off Tabelog in four locales (en/tw/kr/th). 東京都新宿区新宿3-22-12 新宿サンパークビル5F; NINETY-NINE seats (10 counter, 59 table, 30 in private rooms); 10:30–23:00 every day of the year, L.O. 22:15; average spend ¥2,000–2,999 at dinner and ¥1,000–1,999 at lunch, over 1,098 ratings. Cuisine 洋食 / 食堂. ⚠ THE HARVEST RETURNED 82 ROWS AND ONLY 56 ARE DISTINCT DISHES. Two separate problems, both recorded rather than quietly dropped. NINETEEN rows are Tabelog CATEGORY PLACEHOLDERS — a row whose name is identical to its own section heading and which carries no price: "Pasta" in the [Pasta] section, "Curry" in [Curry], "Bento" in [★Bento], "Sashimi" in [Sashimi], "Salad" in [Salad], and a final row simply called "Remarks". These are the menu’s table of contents, not food; the shop evidently publishes those sections as images that Tabelog cannot read. SEVEN more rows are exact duplicates printed twice in the list — Showa Plate, Shrimp Macaroni Gratin, Sanpei Rice, Omurice, and three cup soups all appear in both the opening "revival menu" block and again further down. Recording all 82 would have invented nineteen dishes and double-counted seven. ⚠ IT ALSO MEANS THIS RECORD IS INCOMPLETE BY THE SOURCE’S OWN ADMISSION: the shop demonstrably has pasta, curry, bento, donburi, sashimi, grilled fish and salad sections whose contents are not published as text anywhere Tabelog exposes. What is below is the readable half of a larger menu. ⚠ THE DIETARY STORY IS THE SIMPLEST IN THIS TICK AND THE BLEAKEST: 洋食 IS A ROUX CUISINE. Hayashi sauce is a demi-glace, curry is a flour roux, the macaroni gratin is béchamel, and all three are wheat cooked in fat where the flour IS the sauce. Around them sit panko — menchi katsu, croquette, shrimp fry, white fish fry — and then pizza, pasta and bread. A coeliac reading this menu should understand that the flour is not an additive here but the defining technique of the cuisine; "Japanese-style Western food" is, structurally, flour. ⚠ WHAT IS ACTUALLY REACHABLE: plain rice (three sizes), the fried eggs, grated cheese and Tabasco. That is close to the whole list, and two of those are condiments. The ¥120 miso soup and the ¥450 mini salad are asks. ⚠ FOR A VEGAN THE ROOM IS EFFECTIVELY CLOSED — every sauce is meat-stock-based, the soups are consommé or cream, and the salads are undeclared. ⚠ ONE ROW IS WORTH EXPLAINING BECAUSE NO LOCALE DOES: 三平ライス (row 3) is a 林屋 house invention rather than a standard dish, and none of the four translations says what is in it. It is recorded as unknown composition rather than guessed at.',
  last_checked: T,
  items: [
    { ja: '昭和プレート', romaji: 'showa plate', en: 'Showa plate (mixed yoshoku plate)', price: 'JPY 1,680', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: `A combination plate of the shop’s Showa-era classics. A 洋食 combination plate is by construction several fried and sauced items at once — hamburg, a fry, a croquette — so it aggregates every wheat route on the menu onto one dish.${FRYER}`, dish_key: 'showa_plate' },
    { ja: '海老マカロニグラタン', romaji: 'ebi macaroni gratin', en: 'Shrimp macaroni gratin', price: 'JPY 1,430', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: `Macaroni is wheat pasta and a gratin is bound with béchamel — butter, FLOUR and milk.${ROUX} Dairy and shrimp as well.`, dish_key: 'ebi_macaroni_gratin' },
    { ja: '三平ライス', romaji: 'sanpei rice', en: 'Sanpei rice (house speciality, composition unpublished)', price: 'JPY 1,180', section: 'Revival Menu', gf: 'ask', vegan: 'ask',
      note: '⚠ A house invention, not a standard dish, and NOT ONE OF THE FOUR LOCALES EXPLAINS IT — en, tw, kr and th all simply transliterate the name. The shop publishes no description. Recorded as unknown rather than guessed: at a 洋食 counter the odds strongly favour a rice dish under a demi-glace or curry sauce, both of which would be roux, but that is inference and not evidence. Ask.', dish_key: 'sanpei_rice' },
    { ja: 'オムライス', romaji: 'omurice', en: 'Omurice', price: 'JPY 980', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: '⚠ The rice inside is fried with ketchup and is usually gluten-free; the problem is what goes over it, which at this shop is demi-glace or hayashi sauce — both roux. A plain ケチャップ omurice would be a genuine possibility and the kitchen can make one; as listed it is sauced. Egg throughout, so never vegan.', dish_key: 'omurice' },
    { ja: '牛角煮シチュー', romaji: 'gyu kakuni stew', en: 'Braised beef stew', price: 'JPY 2,780', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: `The most expensive dish on the readable menu. A 洋食 stew is a demi-glace reduction.${ROUX}`, dish_key: 'gyu_kakuni_stew' },
    { ja: '黒毛和牛すね肉の赤ワイン煮', romaji: 'kuroge wagyu sune-niku no akawine ni', en: 'Black wagyu shank braised in red wine', price: 'JPY 2,680', section: 'Revival Menu', gf: 'ask', vegan: 'no',
      note: '⚠ THE ONE EXPENSIVE DISH HERE WORTH ASKING ABOUT. A red-wine braise is beef, wine, vegetables and time — no flour is required by the method, unlike the demi-glace dishes around it. Many 洋食 kitchens nevertheless finish it with a demi-glace or thicken it with a beurre manié. This is the only main on the menu where the answer could plausibly be yes.', dish_key: 'wagyu_akawine_ni' },
    { ja: '海老フライ定食', romaji: 'ebi fry teishoku', en: 'Shrimp fry set meal', price: 'JPY 1,680', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: `Panko-crumbed prawns — panko is bread — with rice, miso soup and pickles.${FRYER} Usually served with a wheat-containing tonkatsu or tartare sauce.`, dish_key: 'ebi_fry_teishoku' },
    { ja: 'チーズハンバーグ', romaji: 'cheese hamburg', en: 'Cheese hamburg steak', price: 'JPY 1,180', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: '⚠ A Japanese ハンバーグ is BOUND with panko soaked in milk — the breadcrumb is mixed into the patty, not coating it — and then napped with demi-glace. Wheat inside and outside. Dairy as well.', dish_key: 'cheese_hamburg' },
    { ja: '特製ビーフメンチカツ', romaji: 'tokusei beef menchi katsu', en: 'Special beef menchi katsu', price: 'JPY 1,680', section: 'Revival Menu', gf: 'no', vegan: 'no',
      note: `メンチカツ is minced beef bound with panko and then crumbed in panko again before frying.${FRYER}`, dish_key: 'beef_menchi_katsu' },
    { ja: 'ボルシチ', romaji: 'borscht', en: 'Borscht', price: 'JPY 580', section: 'Add-ons', gf: 'ask', vegan: 'no',
      note: '⚠ An unusual row for a Tokyo 洋食 diner and a better prospect than most: borscht is beetroot, cabbage and root vegetables in a beef stock — no flour is needed by the recipe. Soured cream on top makes it non-vegan, and some kitchens thicken it. Worth asking.', dish_key: 'borscht' },
    { ja: 'カップコーンスープ', romaji: 'cup corn soup', en: 'Cup corn soup', price: 'JPY 280', section: 'Add-ons', gf: 'ask', vegan: 'no',
      note: 'Japanese corn potage is cream-based and frequently roux-thickened; many are made from a bought powder base containing wheat. Dairy, so not vegan.', dish_key: 'cup_corn_soup' },
    { ja: 'カップクリームチーズスープ', romaji: 'cup cream cheese soup', en: 'Cup cream cheese soup', price: 'JPY 280', section: 'Add-ons', gf: 'ask', vegan: 'no',
      note: 'A cream soup, so dairy. Usually thickened, often with flour.', dish_key: 'cup_cream_cheese_soup' },
    { ja: 'カップビーフコンソメスープ', romaji: 'cup beef consomme soup', en: 'Cup beef consommé', price: 'JPY 120', section: 'Add-ons', gf: 'ask', vegan: 'no',
      note: '⚠ The cheapest row on the menu and the most promising of the three soups: a true consommé is clarified stock with no flour at all. The caveat is that a ¥120 cup is likely made from a commercial base, and bouillon powders very often contain wheat. Beef stock, so never vegan.', dish_key: 'cup_beef_consomme' },
    { ja: 'ミニカレー', romaji: 'mini curry', en: 'Mini curry', price: 'JPY 500', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `A small portion of the house curry.${ROUX}`, dish_key: 'mini_curry' },
    { ja: 'ミニハヤシ', romaji: 'mini hayashi', en: 'Mini hayashi', price: 'JPY 580', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `Hayashi sauce is a demi-glace — beef, onion, tomato and a brown roux.${ROUX}`, dish_key: 'mini_hayashi' },
    { ja: 'ミニうどん', romaji: 'mini udon', en: 'Mini udon', price: 'JPY 450', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: 'Udon is 100% wheat flour, in a dashi-and-soy broth. The single Japanese noodle row on a Western menu.', dish_key: 'mini_udon' },
    { ja: 'ミニサラダ', romaji: 'mini salad', en: 'Mini salad', price: 'JPY 450', section: 'Add-ons', gf: 'ask', vegan: 'ask',
      note: '⚠ One of only two asks on this menu that could come back a yes for both diets. Leaves are leaves; the dressing decides, and a 洋食 diner’s house dressing is typically a soy-based Japanese one (wheat) or a creamy sesame one (egg and dairy). Ask for oil and vinegar. Watch for croutons.', dish_key: 'mini_salad' },
    { ja: 'カレーソース', romaji: 'curry sauce', en: 'Curry sauce (extra)', price: 'JPY 430', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `Sold as a sauce on its own, which makes the construction explicit.${ROUX}`, dish_key: 'curry_sauce' },
    { ja: 'ハヤシソース', romaji: 'hayashi sauce', en: 'Hayashi sauce (extra)', price: 'JPY 460', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `Demi-glace sold separately.${ROUX}`, dish_key: 'hayashi_sauce' },
    { ja: '目玉焼き S', romaji: 'medamayaki S', en: 'Fried egg, single', price: 'JPY 150', section: 'Add-ons', gf: 'gf', vegan: 'no',
      note: '⚠ A fried egg, and one of the very few unconditionally gluten-free items on this menu. Egg and a pan. Never vegan.', dish_key: 'medamayaki_s' },
    { ja: '目玉焼き W', romaji: 'medamayaki W', en: 'Fried egg, double', price: 'JPY 300', section: 'Add-ons', gf: 'gf', vegan: 'no',
      note: 'Two eggs. Same reading.', dish_key: 'medamayaki_w' },
    { ja: '海老フライ', romaji: 'ebi fry', en: 'Shrimp fry (add-on, 1 piece)', price: 'JPY 480', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `Panko-crumbed prawn, sold both as an add-on here and as a snack in the 揚げ物 section at the same price.${FRYER}`, dish_key: 'ebi_fry' },
    { ja: 'メンチカツ', romaji: 'menchi katsu', en: 'Minced meat cutlet (add-on)', price: 'JPY 360', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `Panko inside the patty and panko outside it.${FRYER}`, dish_key: 'menchi_katsu' },
    { ja: 'カニクリームコロッケ', romaji: 'kani cream korokke', en: 'Crab cream croquette (add-on)', price: 'JPY 380', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `⚠ Wheat twice and in different forms: the filling is a stiff BÉCHAMEL (butter, flour, milk) and the coating is panko.${ROUX}${FRYER} Crab and dairy as well.`, dish_key: 'kani_cream_korokke' },
    { ja: '白身魚フライ', romaji: 'shiromi-zakana fry', en: 'White fish fry (add-on)', price: 'JPY 360', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: `Panko-crumbed white fish.${FRYER}`, dish_key: 'shiromi_fry' },
    { ja: 'ハンバーグ', romaji: 'hamburg', en: 'Hamburg steak (add-on)', price: '(no price printed)', section: 'Add-ons', gf: 'no', vegan: 'no',
      note: 'The patty as an add-on; no price printed on this row. Panko-bound, demi-glace-napped.', dish_key: 'hamburg_addon' },
    { ja: 'パン', romaji: 'pan', en: 'Bread', price: 'JPY 320', section: 'Add-ons', gf: 'no', vegan: 'ask',
      note: 'Bread. Wheat by definition. Vegan is an ask only because a plain roll may or may not contain milk or butter.', dish_key: 'pan' },
    { ja: 'パン用バター or オリーブオイル', romaji: 'pan-yo butter or olive oil', en: 'Butter or olive oil for bread', price: 'JPY 90', section: 'Add-ons', gf: 'gf', vegan: 'ask',
      note: '⚠ A small but genuinely useful row: the shop offers OLIVE OIL as an alternative to butter, which is a vegan choice being made available by the menu rather than by request. Both options are gluten-free; the olive oil is vegan and the butter is not. Ordered without the bread it is simply a condiment.', dish_key: 'butter_or_olive_oil' },
    { ja: 'ライス', romaji: 'raisu', en: 'Rice', price: 'JPY 280', section: 'Add-ons', gf: 'gf', vegan: 'vegan',
      note: '⚠ Plain boiled white rice — clean on both counts, and with the fried eggs the only unconditional yes on this menu. The shop sells it in three sizes, which at least means a diner who can eat nothing else is not stuck with one portion.', dish_key: 'raisu' },
    { ja: '大盛ライス', romaji: 'omori raisu', en: 'Large rice', price: 'JPY 420', section: 'Add-ons', gf: 'gf', vegan: 'vegan',
      note: 'Large portion of plain rice. Clean on both counts.', dish_key: 'omori_raisu' },
    { ja: '小ライス', romaji: 'ko raisu', en: 'Small rice', price: 'JPY 190', section: 'Add-ons', gf: 'gf', vegan: 'vegan',
      note: 'Small portion of plain rice. Clean on both counts.', dish_key: 'ko_raisu' },
    { ja: '味噌汁', romaji: 'miso shiru', en: 'Miso soup', price: 'JPY 120', section: 'Add-ons', gf: 'ask', vegan: 'ask',
      note: 'Miso may be rice-fermented (gluten-free) or barley/wheat-fermented; the dashi is bonito unless it is kombu. Both questions are answerable, which makes this an ask rather than a no — but a 食堂 miso soup is katsuo dashi with near-certainty.', dish_key: 'miso_shiru' },
    { ja: 'タバスコ', romaji: 'tabasco', en: 'Tabasco', price: 'JPY 60', section: 'Add-ons', gf: 'gf', vegan: 'vegan',
      note: 'Tabasco is chilli, vinegar and salt — gluten-free and vegan. Listed here because the shop charges for it, and because on a menu this closed it is worth knowing which condiments are clean.', dish_key: 'tabasco' },
    { ja: '粉チーズ', romaji: 'kona cheese', en: 'Grated cheese', price: 'JPY 90', section: 'Add-ons', gf: 'ask', vegan: 'no',
      note: '⚠ Hard cheese is gluten-free, but grated and powdered cheeses frequently carry an anti-caking agent, and cellulose or starch fillers are not always wheat-free. Dairy, so not vegan.', dish_key: 'kona_cheese' },
    { ja: 'フィッシュ＆チップス', romaji: 'fish and chips', en: 'Fish and chips', price: 'JPY 880', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `A flour-and-beer batter around the fish.${FRYER}`, dish_key: 'fish_and_chips' },
    { ja: 'チーズフライ', romaji: 'cheese fry', en: 'Fried cheese', price: 'JPY 680', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `Crumbed and fried cheese.${FRYER} Dairy.`, dish_key: 'cheese_fry' },
    { ja: 'フライドポテト', romaji: 'furaido poteto', en: 'French fries', price: 'JPY 600', section: 'Fried Food', gf: 'ask', vegan: 'ask',
      note: '⚠ Potato and oil, clean in principle on both counts — but this section fries panko cutlets, battered fish and croquettes in what is certainly shared oil at a 99-seat diner. Treat as contaminated for coeliac purposes unless the shop confirms a separate fryer.', dish_key: 'furaido_poteto' },
    { ja: 'スパイシーポテト', romaji: 'spicy potato', en: 'Spicy potato', price: 'JPY 680', section: 'Fried Food', gf: 'ask', vegan: 'ask',
      note: 'Seasoned fries. Same shared-fryer problem, plus a spice mix that may be flour-bulked.', dish_key: 'spicy_potato' },
    { ja: 'オニオンリングフライ', romaji: 'onion ring fry', en: 'Onion rings', price: 'JPY 750', section: 'Fried Food', gf: 'no', vegan: 'ask',
      note: '⚠ The onion is vegan and the batter usually is too, which makes this one of the few plausibly vegan hot dishes here — but the batter is flour, so it is a flat no for gluten. Check for egg or milk in the batter.', dish_key: 'onion_ring' },
    { ja: '白身魚フライスナック', romaji: 'shiromi-zakana fry snack', en: 'Fried white fish snack', price: 'JPY 680', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `Crumbed white fish as a drinking snack.${FRYER}`, dish_key: 'shiromi_fry_snack' },
    { ja: '鶏の唐揚げ', romaji: 'tori no karaage', en: 'Chicken karaage', price: 'JPY 780', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `Soy-marinated and dusted before frying — the soy is absorbed into the meat, so changing the coating would not help.${FRYER}`, dish_key: 'karaage' },
    { ja: 'スパイシー鶏の唐揚げ', romaji: 'spicy tori no karaage', en: 'Spicy chicken karaage', price: 'JPY 850', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `The same karaage with a spice coating.${FRYER}`, dish_key: 'spicy_karaage' },
    { ja: '海老フライ（1本）', romaji: 'ebi fry (1 pon)', en: 'Shrimp fry, 1 piece', price: 'JPY 480', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `The same panko prawn sold as a snack rather than an add-on, at the same ¥480.${FRYER}`, dish_key: 'ebi_fry_snack' },
    { ja: 'メンチカツスナック（2個）', romaji: 'menchi katsu snack (2 ko)', en: 'Minced meat cutlet snack, 2 pieces', price: 'JPY 720', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `Two menchi katsu.${FRYER}`, dish_key: 'menchi_katsu_snack' },
    { ja: 'カニクリームコロッケ（2個）', romaji: 'kani cream korokke (2 ko)', en: 'Crab cream croquette, 2 pieces', price: 'JPY 760', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `Béchamel filling, panko coating.${ROUX}${FRYER}`, dish_key: 'kani_korokke_snack' },
    { ja: '白身魚フライ（2個）', romaji: 'shiromi-zakana fry (2 ko)', en: 'White fish fry, 2 pieces', price: 'JPY 720', section: 'Fried Food', gf: 'no', vegan: 'no',
      note: `Two panko-crumbed fish pieces.${FRYER}`, dish_key: 'shiromi_fry_2' },
    { ja: 'マルゲリータピザ', romaji: 'margherita pizza', en: 'Margherita pizza', price: 'JPY 980', section: 'Pizza', gf: 'no', vegan: 'no',
      note: 'Wheat base, mozzarella. No on both counts.', dish_key: 'margherita_pizza' },
    { ja: 'ガーリックピザ', romaji: 'garlic pizza', en: 'Garlic pizza', price: 'JPY 960', section: 'Pizza', gf: 'no', vegan: 'ask',
      note: '⚠ The one pizza that might be dairy-free — a garlic pizza is sometimes just base, oil and garlic — but the base is wheat regardless, so it remains a flat no for gluten.', dish_key: 'garlic_pizza' },
    { ja: 'ミックスピザ', romaji: 'mixed pizza', en: 'Mixed pizza', price: 'JPY 980', section: 'Pizza', gf: 'no', vegan: 'no',
      note: 'Wheat base with mixed toppings, normally including salami and cheese.', dish_key: 'mixed_pizza' },
    { ja: 'サラミピザ', romaji: 'salami pizza', en: 'Salami pizza', price: 'JPY 970', section: 'Pizza', gf: 'no', vegan: 'no',
      note: 'Wheat base, cured pork, cheese.', dish_key: 'salami_pizza' },
    { ja: 'シーフードピザ', romaji: 'seafood pizza', en: 'Seafood pizza', price: 'JPY 1,080', section: 'Pizza', gf: 'no', vegan: 'no',
      note: 'Wheat base with seafood. The most expensive pizza.', dish_key: 'seafood_pizza' },
    { ja: 'ハヤシライス', romaji: 'hayashi rice', en: 'Hayashi rice', price: 'JPY 980', section: 'Hayashi / Omurice', gf: 'no', vegan: 'no',
      note: `The shop’s namesake dish: beef and onion in a demi-glace over rice.${ROUX}`, dish_key: 'hayashi_rice' },
    { ja: 'オムハヤシ', romaji: 'omu hayashi', en: 'Omurice with hayashi sauce', price: 'JPY 1,480', section: 'Hayashi / Omurice', gf: 'no', vegan: 'no',
      note: `Omurice under hayashi sauce — the two signature dishes combined, and the roux with them.${ROUX}`, dish_key: 'omu_hayashi' },
    { ja: 'スープ＆サラダセット', romaji: 'soup and salad set', en: 'Soup and salad set', price: 'JPY 220', section: 'Sets', gf: 'ask', vegan: 'ask',
      note: '⚠ At ¥220 the best-value row on the menu, and an ask on both counts rather than a no — but it is two asks stacked, since neither which soup nor which dressing is specified. Given the three cup soups above are corn, cream cheese and beef consommé, none is vegan. Ask precisely.', dish_key: 'soup_salad_set' },
  ],
});
