// Local tick 2026-09-11 — honest empties, part C: izakaya, Chinese/Taiwanese, outliers.
// Same verification as parts A and B: JA listing + /en/, all four menu sub-tabs, all empty.
import { put, T } from './_tick_lib.mjs';
const M = u => `https://tabelog.com/tokyo/${u}/dtlmenu/`;
const NOMENU =
  'Tabelog prints 「No Menu」 and carries zero menu rows. Checked on the Japanese listing as well as /en/, and across all four menu sub-tabs — food, lunch, drink and course — all empty. The selector was re-verified in the same pass against a shop that does publish, so this is the shop publishing nothing, not a fetch failure. No first-party site is on record for it: the Tabelog page IS the website field, and Tabelog’s own listing page sits behind a Cloudflare challenge, so the official-homepage link it would normally carry could not be read. An honest empty, not an unfinished record.';

// ── Listings Tabelog has flagged ───────────────────────────────────────────────
put('s19', 'tokyo_torisen', {
  verified: 'provisional', confidence: 'low', sources: [M('A1311/A131102/13082586')],
  price_note: `${NOMENU} ⚠ THIS LISTING ALSO CARRIES TABELOG’S RED 「掲載保留」 (LISTING ON HOLD) BADGE, WHICH IS A SEPARATE AND MORE IMPORTANT FINDING THAN THE MISSING MENU. On hold means Tabelog has stopped standing behind the listing — typically because the shop has moved, closed, or stopped responding — and the site explains it with boilerplate reading "may have relocated or permanently closed". ⚠ THAT SENTENCE IS BOILERPLATE, NOT A CLOSURE REPORT: it appears verbatim on every on-hold listing, and an earlier pass of this dataset mis-read it as a closure marker for this very shop. 鳥せん is NOT recorded as closed here. What is true is that its operating status is unconfirmed and should be checked by phone before anyone is sent. 東京都台東区浅草3-35-9; cuisine 日本料理; average spend ¥3,000–3,999. 鳥 in the name points at a chicken house, which would put it in the same 塩-or-タレ territory as a yakitori counter, but with no menu and no confirmed status that is inference rather than research.`,
  last_checked: T, items: [] });

put('s23', 'tokyo_pota_pasta_shibuya_dogen', {
  verified: 'provisional', confidence: 'low', sources: [M('A1303/A130301/13193965')],
  price_note: `${NOMENU} ⚠ ALSO CARRIES THE RED 「掲載保留」 (LISTING ON HOLD) BADGE — operating status unconfirmed by Tabelog. As with 鳥せん, the accompanying "may have relocated or permanently closed" sentence is site boilerplate shown on every on-hold listing and is NOT a closure report; this shop is not recorded as closed. 東京都渋谷区道玄坂2-6-7 2F・3F; cuisine パスタ; average spend UNDER ¥999, which for a two-floor Dogenzaka site marks it as a fast-casual counter rather than a restaurant. ⚠ For a coeliac, a sub-¥999 pasta counter is a straightforward no — dried wheat pasta is the entire product and a gluten-free line at that price point would be the shop’s headline claim, not an unpublished detail. For a vegan it is more open than most of this batch: a plain tomato or oil-and-garlic sauce is often incidentally vegan, though the standard traps apply (parmesan stirred through, butter finishing the pan, and a broth base in the sauce). Nothing published to confirm any of it, and the status question comes first anyway.`,
  last_checked: T, items: [] });

// ── Izakaya and general Japanese ──────────────────────────────────────────────
for (const [shard, id, url, addr, band, note] of [
  ['s18', 'tokyo_shuzo', 'A1304/A130401/13159181', '東京都新宿区西新宿7-19-22 新宿ダイカンプラザシティ1F', '¥4,000–4,999',
   '日本料理 / 居酒屋. ⚠ 居酒屋 IS THE HARDEST CATEGORY IN THIS DATASET TO RECORD HONESTLY, AND IT IS WORTH SAYING WHY RATHER THAN LEAVING A BLANK. An izakaya menu is thirty to sixty small plates that change with what came in, which is exactly why so many of them publish nothing — there is no stable list to publish. The dietary problem is structural rather than dish-by-dish: 出汁 (bonito) and 醤油 (wheat-brewed soy) are the two seasonings that underlie nearly every plate, including ones that look plain — 冷奴, おひたし, even the pickles — so a coeliac or vegan cannot pick safe-looking items off an izakaya menu by sight. 酒蔵 in the name signals a sake-forward house, which usually means the food is built to accompany drink: salt-grilled fish, pickles and simmered dishes, all of them soy-seasoned.'],
  ['s20', 'tokyo_sakasakana_zuburoku', 'A1311/A131102/13216303', '東京都台東区浅草3-34-3', '¥4,000–4,999',
   '居酒屋. The name 酒肴ずぶろく is literally "sake and the food you eat with it" — a drink-led counter. Same structural reading as any izakaya: no stable published list, and dashi and wheat-soy under nearly every plate. ⚠ The one category-specific note worth keeping is that a 肴-focused house leans on 塩辛, 干物 and 刺身 — salted and dried seafood — which are gluten-free in themselves but arrive with a soy dish beside them, so the useful question is whether tamari can be brought or requested rather than which dish to order.'],
  ['s23', 'tokyo_asakusa_natsuno', 'A1311/A131102/13196920', '東京都台東区浅草2-5-12 第三夏野ビル1F', 'not published',
   '居酒屋, and Tabelog gives no average-spend band either — so the listing carries essentially nothing beyond the address and the category. ⚠ Note that the building is 第三夏野ビル, the shop’s own name, which means the operator owns or is named for the premises; that is a stability signal, not a dietary one. On the category alone: dashi and wheat-soy underlie the plates, and nothing is published to work from.'],
  ['s27', 'tokyo_sakuma', 'A1311/A131102/13012255', '東京都台東区浅草3-4-2', '¥4,000–4,999',
   '居酒屋 in 浅草. Nothing published beyond category, address and band. The izakaya reading applies unchanged: a rotating small-plate list that is never committed to print, with 出汁 and 醤油 running underneath it. Recorded as an honest empty rather than left in the queue, because the absence here is the shop’s publishing habit and re-fetching will not change it.'],
  ['s28', 'tokyo_nakano', 'A1303/A130301/13075446', '東京都渋谷区宇田川町31-3', '¥6,000–7,999',
   '居酒屋 / 海鮮. ⚠ The 海鮮 tag plus a ¥6,000–7,999 band is the informative combination: this is a seafood-led drinking house at a price where the fish is the draw. For a VEGAN that closes the building. For a coeliac it is more open than it looks — 刺身 is raw fish and 焼き魚 is grilled fish and salt, both clean in themselves — with the whole risk concentrated in what accompanies them: the soy dish, the ポン酢 (usually soy-based), and any 煮付け, which is fish simmered IN soy and therefore not recoverable. Ask, and consider bringing tamari.'],
  ['s31', 'tokyo_shokudo_arata', 'A1310/A131003/13285591', '東京都千代田区神田猿楽町1-2-4 冨田屋ビル1F', 'not published',
   '海鮮 / 食堂 / 居酒屋, no average-spend band published. The 食堂 tag is the one that carries information: a shokudo is a plain daytime canteen serving 定食 — a main, rice, miso soup and pickles — which is a FIXED-COMPOSITION format rather than an à-la-carte one. ⚠ That matters because a teishoku always arrives with miso soup, and miso soup is dashi (fish) and miso (frequently barley- or wheat-fermented), so the two components a diner is least likely to query are the two carrying the problem. The seafood main is usually grilled or simmered; simmered means soy.'],
]) put(shard, id, {
  verified: 'provisional', confidence: 'low', sources: [M(url)],
  price_note: `${NOMENU} ${addr}; average spend ${band}; cuisine ${note}`,
  last_checked: T, items: [] });

// ── Chinese and Taiwanese ─────────────────────────────────────────────────────
for (const [shard, id, url, addr, band, note] of [
  ['s23', 'tokyo_chuka_saibo_daruma', 'A1304/A130401/13037602', '東京都新宿区新宿3-31-5 新宿ペガサス館1F', '¥1,000–1,999',
   '中華 / 食堂 / ラーメン — a 町中華, the neighbourhood Chinese diner. ⚠ THE 町中華 CATEGORY DESERVES ITS OWN WARNING AND IT IS NOT THE OBVIOUS ONE. The wheat is everywhere expected — 中華麺, 餃子 wrappers, 春巻 skins — but the trap a coeliac walks into is 餡かけ, the glossy sauce poured over 中華丼, 天津飯 and あんかけ焼きそば. It is thickened with 片栗粉 (potato starch, which is fine) but built on soy sauce and a chicken-or-pork stock base, and because it is poured over rice it is routinely assumed to be the safe option on the menu. It is not. For a vegan the same sauce is the problem: almost every 町中華 stock is pork or chicken, and even the vegetable stir-fries are finished in it.'],
  ['s24', 'tokyo_shanghai_hanten', 'A1310/A131003/13073568', '東京都千代田区神田三崎町2-19-9 大曽根ビル1F', '¥1,000–1,999',
   '中華. A Kanda-Misakicho Chinese house at canteen prices; the 上海 in the name is a style claim, and Shanghainese cooking leans harder on 醤油 and 老酒 than Cantonese does — red-braising (紅焼) is a soy-and-sugar reduction and is a signature technique rather than an occasional one. ⚠ That makes the wheat-soy exposure higher here than the generic Chinese tag would suggest, not lower. 小籠包, if served, is a wheat wrapper around pork and a gelled pork stock. Nothing published.'],
  ['s25', 'tokyo_tenshin_ranman', 'A1311/A131102/13122798', '東京都台東区西浅草2-17-2', '¥2,000–2,999',
   '餃子 / 点心・飲茶. ⚠ A DUMPLING AND DIM-SUM HOUSE IS A CATEGORY-LEVEL NO FOR A COELIAC AND THE RECORD SHOULD SAY SO PLAINLY: the wrapper is the dish. 餃子 and 焼売 skins are wheat; the steamer is shared; and the dipping sauce is soy and vinegar. The one thing worth flagging as an exception rather than a rule is 蒸し餃子 made with a translucent wrapper — 水晶 or 蝦餃 style — which uses wheat STARCH and tapioca rather than wheat flour and is sometimes genuinely gluten-free, but wheat starch is not reliably gluten-free and no shop that publishes no menu has published which wrapper it uses. For a vegan, dim sum fillings are pork and shrimp by default and the steamer is shared with both.'],
  ['s25', 'tokyo_taipei', 'A1310/A131003/13011063', '東京都千代田区神田三崎町2-19-9 MMビル1F', '¥3,000–3,999',
   '台湾料理. ⚠ TAIWANESE IS THE ONE CUISINE IN THIS BATCH WHERE A COELIAC HAS A REAL STRUCTURAL ADVANTAGE, AND IT IS WORTH RECORDING EVEN WITHOUT A MENU: a great deal of Taiwanese cooking is rice-based rather than wheat-based — 米粉 (rice vermicelli), 碗粿, 蘿蔔糕 (radish cake, rice flour), 滷肉飯 over rice. The catch is that the seasoning that defines the cuisine is 醤油膏, a thickened soy, plus 五香粉 and often 麺輪/麸 (wheat gluten) as a texture ingredient in braises — so the grain arrives through the sauce and through deliberate gluten additions rather than through the staple. ⚠ For a VEGAN, Taiwan is also unusually good ground: the Buddhist 素食 tradition is mainstream there and mock meats are common — but those mock meats are very often seitan, which is pure wheat gluten. The two diets pull in opposite directions here more sharply than anywhere else in this dataset. Nothing published; this shop shares its address block (2-19-9) with 上海飯店 above.'],
]) put(shard, id, {
  verified: 'provisional', confidence: 'low', sources: [M(url)],
  price_note: `${NOMENU} ${addr}; average spend ${band}; cuisine ${note}`,
  last_checked: T, items: [] });

// ── Outliers: the ones that are not a Japanese grain problem ──────────────────
put('s23', 'tokyo_il_lato', {
  verified: 'provisional', confidence: 'low', sources: [M('A1304/A130401/13256289')],
  price_note: `${NOMENU} 東京都新宿区新宿3-6-2 栄ビル4F; cuisine イタリアン; average spend ¥15,000–19,999 — tied with 鮨 然 as the most expensive shop in this batch. At that level an Italian restaurant in Tokyo runs a degustazione, which is again a format with no fixed menu to publish. ⚠ FOR A COELIAC THIS IS A GENUINELY GOOD PROSPECT AND THE REASONING IS DIFFERENT FROM EVERY OTHER SHOP HERE. Italian fine dining is the cuisine most used to the request: Italy screens for coeliac disease at population level, gluten-free pasta is normal rather than exotic, and a kitchen at ¥15,000 a head plates each course individually. The risks are the obvious ones — pasta, bread, and flour-thickened sauces — and all three are substitutable when the kitchen is told in advance. ⚠ Tell them at BOOKING: a tasting menu is bought and prepped to a plan, and a gluten-free pasta course has to be made separately. For a vegan the same logic applies but less reliably, since butter, parmesan and brodo are structural to the cuisine rather than additions to it. No dishes or prices published.`,
  last_checked: T, items: [] });

put('s25', 'tokyo_lodge_akaishi', {
  verified: 'provisional', confidence: 'low', sources: [M('A1311/A131102/13058004')],
  price_note: `${NOMENU} 東京都台東区浅草3-8-4; cuisine 喫茶店 / 洋食 / パスタ; average spend ¥1,000–1,999. A 喫茶店 — an old-style Japanese coffee house — serving 洋食, which is the Meiji-era Japanese reading of Western food. ⚠ 洋食 IS A NEARLY COMPLETE NO FOR A COELIAC AND THE REASON IS THAT ITS THREE SIGNATURE DISHES ARE ALL FLOUR-BUILT: ハヤシライス and カレー are thickened with a wheat ROUX (Japanese curry roux blocks are flour-based, unlike most South Asian curry), コロッケ and メンチカツ are panko-crumbed, and ナポリタン is wheat pasta. The デミグラスソース under almost everything is a roux reduction too. This is the cuisine where "it is just meat and rice" is most often wrong. ⚠ The kissaten side is more open: coffee and トースト aside, a プリン (custard, egg and sugar) is usually gluten-free and is the one thing worth asking about. Nothing published.`,
  last_checked: T, items: [] });

put('s28', 'tokyo_soup_deli', {
  verified: 'provisional', confidence: 'low', sources: [M('A1310/A131003/13048252')],
  price_note: `${NOMENU} 東京都千代田区神田神保町2-34 鳴海ビル1F; cuisine カレー / 洋食 / カフェ, no average-spend band published. ⚠ THE CURRY TAG IS THE WHOLE QUESTION AND IT SPLITS TWO WAYS THAT LOOK IDENTICAL ON A MENU. If this is Japanese-style カレーライス, the sauce is built on a wheat-flour roux and is a flat no. If it is a soup curry or a South Asian style, the base is typically onion, tomato and spice with no flour at all and can be genuinely gluten-free. The shop name — SOUP DELI — points at the second, which would make this one of the more promising records in the batch, but that is an inference from a name and not a finding. ⚠ A soup-led counter is also the most likely place in this batch to have a vegetable soup that is incidentally vegan, with the usual caveats about chicken or pork stock as the base and butter or cream as the finish. Genuinely worth a first-party check if a site is ever found; nothing is published on Tabelog.`,
  last_checked: T, items: [] });

put('s28', 'tokyo_asakusa_himurodo_kakigor_2', {
  verified: 'provisional', confidence: 'low', sources: [M('A1311/A131102/13286202')],
  price_note: `${NOMENU} 東京都台東区浅草3-24-8 クレスト浅草1F; cuisine 甘味処 / かき氷; average spend ¥2,000–2,999 — which is a striking number for shaved ice and marks this as a specialist 氷室 house rather than a summer stall. ⚠ THIS IS THE MOST PROMISING RECORD IN THE ENTIRE NO-MENU BATCH FOR BOTH DIETS AND IT IS THE REASON THIS GROUP WAS NOT WORTH SKIPPING. Kakigori is shaved ice and syrup: no wheat, no dairy and no animal product in the base at all. A coeliac and a vegan can both eat the core product. The risks are all in what is added on top, and they are specific and checkable — 練乳 (condensed milk) and ice cream are dairy; 白玉 (rice-flour dumplings) are fine for gluten but not always for a shared pot; あんこ (sweet red bean) is vegan and gluten-free as made but is sometimes thinned with a wheat-containing syrup; and castella or wafer garnishes are wheat. ⚠ The practical upshot: at a kakigori specialist, a plain 氷いちご or 氷宇治 with no 練乳 is very likely clean for both diets — the single most likely safe order anywhere in this batch. Unconfirmed: the shop publishes no flavour list, no prices and no allergen statement.`,
  last_checked: T, items: [] });

put('s37', 'tokyo_tanagokoro', {
  verified: 'provisional', confidence: 'low', sources: [M('A1311/A131102/13287004')],
  price_note: `${NOMENU} 東京都台東区花川戸1-10-3; cuisine おにぎり, no average-spend band published. ⚠ SECOND-BEST PROSPECT IN THIS BATCH AFTER THE KAKIGORI HOUSE, AND FOR A SIMILAR REASON: an onigiri is rice, salt and nori around a filling, and all three of those are gluten-free and two of the three are vegan. The grain question is settled by the category itself. ⚠ The risk moves entirely into the FILLING, and the fillings sort cleanly into three groups worth knowing in advance. Safe on both counts: 塩むすび (salt only), 梅 (pickled plum), 昆布 — though kombu tsukudani is simmered in soy and is therefore wheat unless tamari. Gluten-free but not vegan: 鮭 (grilled salmon), 明太子, おかか (bonito flakes, usually dressed with soy). Neither: anything 天むす (tempura shrimp, wheat batter), from a フライ filling, or mayonnaise-bound like ツナマヨ (egg). ⚠ The nori itself is plain seaweed and clean, but 味付け海苔 — seasoned nori — is brushed with soy. A shop this focused is also small enough that the staff genuinely know every filling, which makes asking productive here in a way it is not at a ramen counter. Nothing published; worth a first-party check if a site turns up.`,
  last_checked: T, items: [] });
